"use client";
import { useEffect, useRef, useState, type ReactNode } from "react";
import { ArrowRight, Bell, Camera, Copy, Download, Info, Printer, QrCode, ScanLine, X } from "lucide-react";
import QRCode from "qrcode";
import type { IScannerControls } from "@zxing/browser";
import { Select } from "./select";
import { dateLabel, departmentPath } from "./risk-model";
import type { ImportRecords } from "./bulk-import";
import { parseQr, qrUrl, type QrTarget, type fieldReminders } from "./field-access-model";

function Overlay({ children, title, close }: { children: ReactNode; title: string; close: () => void }) {
  const ref = useRef<HTMLDivElement>(null), callback = useRef(close); callback.current = close;
  useEffect(() => { const prev = document.activeElement as HTMLElement; ref.current?.querySelector<HTMLElement>("button")?.focus(); const key = (e: KeyboardEvent) => { if (e.key === "Escape") callback.current(); if (e.key === "Tab") { const list = Array.from(ref.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),[tabindex="0"]') || []).filter(el => el.getClientRects().length); if (e.shiftKey && document.activeElement === list[0]) { e.preventDefault(); list.at(-1)?.focus(); } else if (!e.shiftKey && document.activeElement === list.at(-1)) { e.preventDefault(); list[0]?.focus(); } } }; document.addEventListener("keydown", key); return () => { document.removeEventListener("keydown", key); prev?.focus(); }; }, []);
  return <div className="field-overlay" onMouseDown={e => { if (e.target === e.currentTarget) close(); }}><div ref={ref} className="field-dialog" role="dialog" aria-modal="true" aria-label={title}><header><div><small>OLEOQ / FIELD ACCESS</small><h2>{title}</h2></div><button aria-label={`Close ${title}`} onClick={close}><X size={19}/></button></header>{children}</div></div>;
}
const esc = (value: string) => value.replace(/[&<>"']/g, x => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&apos;" })[x]!);
function saveFile(content: string, filename: string, mime: string) { const url = URL.createObjectURL(new Blob([content], { type: mime })); const a = document.createElement("a"); a.href = url; a.download = filename; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }

export function QrLabelButton({ target, title, area, owner, due, onOpen }: { target: QrTarget; title: string; area: string; owner: string; due: string; onOpen?: (target: QrTarget) => void }) {
  const [open, setOpen] = useState(false), [base, setBase] = useState(""), [image, setImage] = useState(""), [svg, setSvg] = useState(""), [error, setError] = useState(""), [message, setMessage] = useState("");
  let url = ""; try { if (base) url = qrUrl(base, target); } catch { /* Displayed in effect. */ }
  useEffect(() => { if (!open) return; let cancelled = false; setImage(""); setSvg(""); setError(""); setMessage(""); try { const link = qrUrl(base, target); Promise.all([QRCode.toDataURL(link, { errorCorrectionLevel: "M", margin: 4, width: 360 }), QRCode.toString(link, { type: "svg", errorCorrectionLevel: "M", margin: 4, width: 360 })]).then(([png, vector]) => { if (!cancelled) { setImage(png); setSvg(vector); } }).catch(() => { if (!cancelled) setError("Could not generate this label. Check the website address."); }); } catch (e) { setError((e as Error).message); } return () => { cancelled = true; }; }, [open, base, target.kind, target.id]);
  const download = () => { const label = `<svg xmlns="http://www.w3.org/2000/svg" width="420" height="530" viewBox="0 0 420 530"><rect width="420" height="530" fill="white"/><text x="210" y="30" text-anchor="middle" font-family="Arial" font-size="17" font-weight="bold">${esc(area.slice(0, 44) || title.slice(0, 44))}</text><g transform="translate(30 42)">${svg}</g><text x="210" y="426" text-anchor="middle" font-family="Arial" font-size="15">${target.kind === "risk" ? "Risk assessment" : "Inspection"} · ${esc(target.id)}</text><text x="210" y="455" text-anchor="middle" font-family="Arial" font-size="12">Scan in OleoQ to open the current record</text><text x="210" y="480" text-anchor="middle" font-family="Arial" font-size="11">Northstar Manufacturing · Sign-in required</text><text x="210" y="505" text-anchor="middle" font-family="Arial" font-size="11">${esc(new URL(url).host)}</text></svg>`; saveFile(label, `${target.id}-qr-label.svg`, "image/svg+xml;charset=utf-8"); setMessage("Label prepared for download. Print on a white background and keep the clear border."); };
  return <><button type="button" className="rk-button" onClick={() => { setBase(window.location.origin + window.location.pathname); setOpen(true); }}><QrCode size={16}/>QR label</button>{open && <Overlay title="Equipment QR label" close={() => setOpen(false)}><p className="field-intro">Attach this label to the equipment. A scan opens its linked {target.kind === "risk" ? "assessment" : "inspection questionnaire"} after sign-in.</p><div className="qr-print-label"><span className="qr-label-kicker">NORTHSTAR MANUFACTURING</span><h3>{area || title}</h3>{image ? <img width="250" height="250" src={image} alt={`Scannable ${target.kind} QR label for ${target.id}`}/> : <div className="qr-placeholder"><QrCode size={45}/><span>Preparing QR code…</span></div>}<strong>{target.kind === "risk" ? "Risk assessment" : "Inspection"} · {target.id}</strong><p>Scan in OleoQ · Sign-in required</p></div><div className="field-meta"><span><small>Responsible</small><strong>{owner}</strong></span><span><small>Current due date</small><strong>{dateLabel(due)}</strong></span></div>{target.kind === "inspection" && <p className="field-note"><Info size={15}/>Repeat inspections keep this label reference. Scanning opens the earliest outstanding check; if all checks are complete, repeat from the completed record.</p>}<label className="field-input">Label website address<input type="url" value={base} onChange={e => setBase(e.target.value)} placeholder="https://your-workspace.example"/></label><p className="field-note">For a phone, use the deployed HTTPS website address. A localhost link works only on this computer. New demo records are not shared between devices.</p><label className="field-input">Encoded record link<input readOnly value={url}/></label>{error && <p className="rk-error" role="alert">{error}</p>}{message && <p className="field-success" role="status">{message}</p>}<div className="field-actions"><button className="page-primary" disabled={!svg} onClick={download}><Download size={16}/>Download label</button><button className="rk-button" disabled={!image} onClick={() => window.print()}><Printer size={16}/>Print</button><button className="rk-button" disabled={!url} onClick={async () => { try { await navigator.clipboard.writeText(url); setMessage("Record link copied."); } catch { setMessage("Select and copy the record link above."); } }}><Copy size={15}/>Copy link</button>{onOpen && <button className="rk-button" onClick={() => { onOpen(target); setOpen(false); }}>Test QR link <ArrowRight size={15}/></button>}</div></Overlay>}</>;
}

export function QrScanner({ close, onOpen }: { close: () => void; onOpen: (target: QrTarget) => boolean }) {
  const [text, setText] = useState(""), [error, setError] = useState(""), [state, setState] = useState<"idle" | "starting" | "scanning">("idle");
  const video = useRef<HTMLVideoElement>(null), controls = useRef<IScannerControls | null>(null), stream = useRef<MediaStream | null>(null), generation = useRef(0), found = useRef(false);
  const stop = () => { generation.current++; controls.current?.stop(); controls.current = null; stream.current?.getTracks().forEach(t => t.stop()); stream.current = null; setState("idle"); };
  useEffect(() => () => { generation.current++; controls.current?.stop(); stream.current?.getTracks().forEach(t => t.stop()); }, []);
  const open = (value: string) => { try { const target = parseQr(value, window.location.href); stop(); if (!onOpen(target)) { setError("This record is unavailable in the current demo session. Try a seeded record, such as INS-LAD001, or check the correct workspace."); return; } close(); } catch (e) { setError((e as Error).message); } };
  const start = async () => { stop(); const token = generation.current; setError(""); found.current = false; setState("starting"); try { if (!window.isSecureContext || !navigator.mediaDevices?.getUserMedia) throw Error("Camera scanning needs HTTPS (or localhost) and a browser with camera access. You can use a QR image or record reference below."); const { BrowserQRCodeReader } = await import("@zxing/browser"); if (token !== generation.current) return; const media = await navigator.mediaDevices.getUserMedia({ video: { facingMode: { ideal: "environment" } }, audio: false }); if (token !== generation.current) { media.getTracks().forEach(t => t.stop()); return; } stream.current = media; const reader = new BrowserQRCodeReader(); const c = await reader.decodeFromStream(media, video.current!, result => { if (result && !found.current && token === generation.current) { found.current = true; open(result.getText()); } }); if (token !== generation.current) c.stop(); else { controls.current = c; setState("scanning"); } } catch (e) { if (token !== generation.current) return; stop(); const name = (e as Error).name; setError(name === "NotAllowedError" ? "Camera permission was denied. Allow camera access in your browser, or use an image or reference below." : name === "NotFoundError" ? "No camera was found. Use a QR image or reference below." : (e as Error).message || "Could not start the camera."); } };
  const photo = async (file?: File) => { if (!file) return; stop(); setError(""); if (!file.type.startsWith("image/")) { setError("Choose a photograph or PNG image of a QR label."); return; } const token = generation.current, src = URL.createObjectURL(file); try { const { BrowserQRCodeReader } = await import("@zxing/browser"); const result = await new BrowserQRCodeReader().decodeFromImageUrl(src); if (token === generation.current) open(result.getText()); } catch { if (token === generation.current) setError("No readable QR code found. Include the whole label and its white border, or enter the printed reference."); } finally { URL.revokeObjectURL(src); } };
  return <Overlay title="Scan a QR label" close={() => { stop(); close(); }}><p className="field-intro">Walk up to the equipment and scan its label. The assessment or current inspection questionnaire opens here.</p><div className={`field-camera ${state}`}><video ref={video} muted playsInline aria-label="QR camera preview"/>{state !== "scanning" && <div><ScanLine size={45}/><strong>{state === "starting" ? "Starting camera…" : "Point your phone at an OleoQ label"}</strong></div>}</div><div className="field-actions"><button className="page-primary" disabled={state !== "idle"} onClick={start}><Camera size={16}/>Start camera</button>{state !== "idle" && <button className="rk-button" onClick={stop}>Stop camera</button>}</div><label className="field-input">Or choose a QR image<input type="file" accept="image/*" onChange={e => { void photo(e.target.files?.[0]); e.target.value = ""; }}/></label><form onSubmit={e => { e.preventDefault(); open(text); }}><label className="field-input">Record reference or QR link<input value={text} onChange={e => setText(e.target.value)} placeholder="e.g. INS-LAD001 or RA-LAD001" autoCapitalize="characters" autoComplete="off"/></label><button className="rk-button" type="submit">Open record <ArrowRight size={15}/></button></form>{error && <p className="rk-error" role="alert">{error}</p>}<p className="field-note">Camera and image decoding run on this device. A QR label identifies a record; it does not grant access. This presentation uses the demo admin account.</p></Overlay>;
}

export function DueReminderPanel({ items, records, close, onOpen, onJobs }: { items: ReturnType<typeof fieldReminders>; records: ImportRecords; close: () => void; onOpen: (target: QrTarget) => boolean; onJobs: () => void }) {
  const [owner, setOwner] = useState(""); const filtered = items.filter(i => !owner || i.ownerId === owner);
  return <Overlay title="Due-date reminders" close={close}><p className="field-intro">Live in-app preview from enabled reminder rules. Each reminder belongs to the assessment owner or assigned inspector.</p><label className="field-input">Responsible person<Select value={owner} onChange={e => setOwner(e.target.value)}><option value="">All responsible people</option>{records.users.map(u => <option key={u.id} value={u.id}>{u.name}</option>)}</Select></label><div className="field-reminders">{filtered.map(i => <button className="field-reminder" key={`${i.kind}-${i.id}`} onClick={() => { if (onOpen(i.qr)) close(); }}><span className={`field-due ${i.daysUntilDue < 0 ? "overdue" : ""}`}>{i.daysUntilDue < 0 ? `${-i.daysUntilDue} ${i.daysUntilDue === -1 ? "day" : "days"} overdue` : i.daysUntilDue === 0 ? "Due today" : `Due in ${i.daysUntilDue} ${i.daysUntilDue === 1 ? "day" : "days"}`}</span><strong>{i.title}</strong><span>{i.kind === "risk.review" ? "Risk review" : "Inspection"} · {i.id} · {departmentPath(records, i.departmentId).site?.name}</span><small>{records.users.find(u => u.id === i.ownerId)?.name || "Unassigned"} · {dateLabel(i.due)}<ArrowRight size={15}/></small><em>{i.schedules.join(" · ")}</em></button>)}{!filtered.length && <p className="field-note">No due items match the enabled in-app owner reminder rules for this person.</p>}</div><div className="field-actions"><button className="rk-button" onClick={() => { close(); onJobs(); }}><Bell size={15}/>Manage reminder schedules</button></div><p className="field-note">This preview refreshes while the workspace is open. Production cron execution, email delivery and shared records require the backend; no messages are sent from this demo.</p></Overlay>;
}
