import type { ImportRecords } from "./bulk-import";
import type { FormBlueprint } from "./form-builder";
import { addDays, newIncident, recordHistory, snapshot, type Evidence, type IncidentData, type IncidentAction } from "./incident-model";
import { departmentPath, today } from "./risk-model";

export const lawActivities = ["Workplace operations", "Workplace transport", "Machinery", "Chemicals", "Waste", "Air emissions"];
export const lawCategories = ["General", "Workplace transport", "Machinery", "Chemical safety", "Waste", "Emissions"];
export type LawDomain = "Health & Safety" | "Environment" | "Other requirements";
export type LegalPiece = { id: string; title: string; reference: string; jurisdiction: string; domain: Exclude<LawDomain, "Other requirements">; category: string; level: "Primary" | "Secondary" | "Tertiary"; parentId: string; synopsis: string; sourceUrl: string; keywords: string[]; active: boolean };
export type LegalChecklist = { id: string; title: string; domain: LawDomain; category: string; requirements: string; legislationIds: string[]; activityKeys: string[]; keywords: string[]; relatedIds: string[]; active: boolean; profileId?: string };
export type ContentVersion = { version: string; released: string; summary: string; legislation: LegalPiece[]; checklists: LegalChecklist[] };
export type ContentPatch = ContentVersion;
export type LawHistory = { at: string; note: string };
export type LegalProfile = { id: string; name: string; ownerId: string; siteId: string; jurisdiction: string; activities: string[]; description: string; shared: boolean; active: boolean; showCompliance: boolean; version: string; history: LawHistory[] };
export type ChecklistEvaluation = { profileId: string; checklistId: string; relevant: boolean; exclusionReason: string; relevance: string; evaluation: string; score: number | null; ownerId: string; departmentId: string; reviewDate: string; evaluatedAt: string; needsReview: boolean; evidence: Evidence[]; history: LawHistory[] };
export type LawTask = { id: string; profileId: string; checklistId: string; title: string; info: string; ownerId: string; departmentId: string; due: string; priority: "High" | "Medium" | "Low"; completed: boolean; active: boolean; completion: string; history: LawHistory[] };
export type LawLink = { id: string; profileId: string; checklistId: string; kind: "risk" | "incident" | "action"; recordId: string; context: string };
export type LawSource = { profileId: string; checklistId: string; title: string };
export type LawData = { profiles: LegalProfile[]; versions: ContentVersion[]; evaluations: ChecklistEvaluation[]; tasks: LawTask[]; links: LawLink[]; other: LegalChecklist[]; history: LawHistory[] };
export const lawId = (prefix: string) => `${prefix}-${crypto.randomUUID().slice(0, 6).toUpperCase()}`;
export const lawHistory = (note: string): LawHistory => ({ at: new Date().toISOString(), note: `${note} · Alex Morgan` });
export const safeUrl = (url: string) => { try { return ["https:", "http:"].includes(new URL(url).protocol); } catch { return false; } };
const validDate = (v: string) => /^\d{4}-\d{2}-\d{2}$/.test(v) && Number.isFinite(Date.parse(v)) && new Date(`${v}T12:00:00Z`).toISOString().slice(0,10) === v;
const versionRank = (version: string) => /^\d{4}\.Q[1-4]$/.test(version) ? Number(version.slice(0,4))*4 + Number(version.slice(-1)) : 0;
export const latestContent = (data: LawData) => data.versions.at(-1)!;
export const profileContent = (data: LawData, profile: LegalProfile) => data.versions.find(v => v.version === profile.version)!;
export const availableChecklist = (c: LegalChecklist, p: LegalProfile, content: ContentVersion) => c.active && (c.profileId ? c.profileId === p.id : c.activityKeys.some(k => p.activities.includes(k)) && c.legislationIds.some(id => content.legislation.some(l => l.id === id && l.active && l.jurisdiction === p.jurisdiction)));
export function profileChecklists(data: LawData, p: LegalProfile) { const content = profileContent(data,p); return [...content.checklists,...data.other].filter(c => availableChecklist(c,p,content)); }
export function findChecklist(data: LawData, profileId: string, checklistId: string) { const p = data.profiles.find(p => p.id === profileId); return p ? [...profileContent(data,p).checklists,...data.other].find(c => c.id === checklistId) : undefined; }
export function evaluationFor(data: LawData, profileId: string, checklistId: string): ChecklistEvaluation { return data.evaluations.find(e => e.profileId === profileId && e.checklistId === checklistId) || { profileId, checklistId, relevant:true,exclusionReason:"",relevance:"",evaluation:"",score:null,ownerId:data.profiles.find(p=>p.id===profileId)?.ownerId || "user-1",departmentId:"",reviewDate:"",evaluatedAt:"",needsReview:false,evidence:[],history:[] }; }
export const evaluationStatus = (e: ChecklistEvaluation) => !e.relevant ? "Not relevant" : e.needsReview ? "Review required" : e.relevance.trim() && e.evaluation.trim() ? "Complete" : e.relevance.trim() || e.evaluation.trim() ? "Partial" : "Not started";
export const scoreTone = (n: number) => n >= 80 ? "green" : n >= 50 ? "amber" : "red";
export function complianceSummary(data: LawData, p: LegalProfile, domain = "", category = "") { const items = profileChecklists(data,p).filter(c => (!domain || c.domain===domain) && (!category || c.category===category)).map(c=>evaluationFor(data,p.id,c.id)); const relevant=items.filter(e=>e.relevant), scored=relevant.filter(e=>e.score!==null); return { total:relevant.length,excluded:items.length-relevant.length,complete:relevant.filter(e=>evaluationStatus(e)==="Complete").length,review:relevant.filter(e=>e.needsReview || !!e.reviewDate && e.reviewDate<today()).length,rated:scored.length,score:scored.length?Math.round(scored.reduce((sum,e)=>sum+e.score!,0)/scored.length):null }; }
export function saveEvaluation(data: LawData, value: ChecklistEvaluation, reviewed: boolean): LawData {
  if (!value.relevant && !value.exclusionReason.trim()) throw Error("Explain why this checklist is not relevant.");
  if (value.score!==null && (!Number.isFinite(value.score) || !Number.isInteger(value.score) || value.score<0 || value.score>100)) throw Error("Compliance rating must be a whole number from 0 to 100.");
  if (value.reviewDate && !validDate(value.reviewDate)) throw Error("Choose a valid next review date.");
  const complete=!!value.relevance.trim() && !!value.evaluation.trim();
  if (complete && (!value.ownerId || !value.reviewDate || !value.departmentId)) throw Error("Select an owner, department and next review date for a completed evaluation.");
  const next={...snapshot(value),needsReview:value.needsReview && !(reviewed&&complete),evaluatedAt:complete?today():value.evaluatedAt,history:[...value.history,lawHistory(value.relevant?"Evaluation saved" : `Marked not relevant: ${value.exclusionReason}`)]};
  return {...data,evaluations:[...data.evaluations.filter(e=>!(e.profileId===value.profileId&&e.checklistId===value.checklistId)),next]};
}
export function acceptContent(data: LawData, profileId: string): LawData {
  const p=data.profiles.find(p=>p.id===profileId); if (!p) throw Error("Select a legal profile."); const latest=latestContent(data); if (p.version===latest.version) return data;
  const previous=profileContent(data,p); const changed = (id:string) => { const old=previous.checklists.find(c=>c.id===id), next=latest.checklists.find(c=>c.id===id); return JSON.stringify(old)!==JSON.stringify(next) || !!next?.legislationIds.some(l=>JSON.stringify(previous.legislation.find(x=>x.id===l))!==JSON.stringify(latest.legislation.find(x=>x.id===l))); };
  return {...data,profiles:data.profiles.map(x=>x.id===p.id?{...x,version:latest.version,history:[...x.history,lawHistory(`Accepted ${latest.version}; existing evaluations preserved`)]}:x),evaluations:data.evaluations.map(e=>e.profileId===p.id && changed(e.checklistId)?{...e,needsReview:true,history:[...e.history,lawHistory(`Requirements changed in ${latest.version}; review controls and evidence`)]}:e)};
}
export function validateContent(raw: unknown, data: LawData): ContentVersion {
  if (!raw || typeof raw!=="object" || Array.isArray(raw)) throw Error("The file must contain a JSON content package."); const p=raw as Record<string,unknown>;
  const text=(v:unknown)=>typeof v==="string"&&v.trim().length>0; const strings=(v:unknown)=>Array.isArray(v)&&v.every(x=>typeof x==="string");
  if (!text(p.version)||versionRank(p.version as string)<=versionRank(latestContent(data).version)) throw Error("Use a new version in YYYY.Q1–Q4 format, newer than the installed library.");
  if (!text(p.released)||!validDate(p.released as string)||!text(p.summary)) throw Error("Provide a valid release date and a summary.");
  if (!Array.isArray(p.legislation)||!Array.isArray(p.checklists)||!p.legislation.length&&!p.checklists.length) throw Error("Provide legislation and checklist arrays with at least one change.");
  const ids=new Set<string>();
  const legislation=p.legislation.map((v:unknown)=>{if(!v||typeof v!=="object")throw Error("Invalid legislation entry."); const x=v as LegalPiece; if(![x.id,x.title,x.reference,x.jurisdiction,x.synopsis].every(text)||!["Primary","Secondary","Tertiary"].includes(x.level)||!["Health & Safety","Environment"].includes(x.domain)||!lawCategories.includes(x.category)||typeof x.parentId!=="string"||typeof x.active!=="boolean"||!strings(x.keywords)||!safeUrl(x.sourceUrl))throw Error("Each legislation entry needs an ID, title, reference, jurisdiction, synopsis, valid level/domain/category, parentId, keywords, active flag and HTTP(S) source URL."); if(ids.has(x.id))throw Error("Duplicate legislation IDs.");ids.add(x.id);return snapshot(x);});
  ids.clear(); const checklists=p.checklists.map((v:unknown)=>{if(!v||typeof v!=="object")throw Error("Invalid checklist entry."); const c=v as LegalChecklist; if(![c.id,c.title,c.requirements].every(text)||!["Health & Safety","Environment"].includes(c.domain)||!lawCategories.includes(c.category)||!strings(c.legislationIds)||!c.legislationIds.length||!strings(c.activityKeys)||!c.activityKeys.length||c.activityKeys.some(k=>!lawActivities.includes(k))||!strings(c.keywords)||!strings(c.relatedIds)||typeof c.active!=="boolean"||c.profileId)throw Error("Checklists need text, valid domain/category, legislation IDs, supported activity keys, keywords, related IDs and an active flag.");if(ids.has(c.id))throw Error("Duplicate checklist IDs.");ids.add(c.id);return snapshot(c);});
  const previous=latestContent(data); const merge=<T extends {id:string}>(a:T[],b:T[])=>[...a.filter(x=>!b.some(y=>y.id===x.id)),...b];const next={version:p.version as string,released:p.released as string,summary:p.summary as string,legislation:merge(previous.legislation,legislation),checklists:merge(previous.checklists,checklists)};
  for(const l of next.legislation){ const parent=next.legislation.find(x=>x.id===l.parentId);if(l.level==="Primary"&&l.parentId||l.level!=="Primary"&&(!parent||parent.level==="Tertiary"||l.level==="Secondary"&&parent.level!=="Primary"||parent.jurisdiction!==l.jurisdiction))throw Error(`Invalid legislation hierarchy for ${l.id}.`);const seen=new Set([l.id]);let node=parent;while(node){if(seen.has(node.id))throw Error("Legislation hierarchy contains a cycle.");seen.add(node.id);node=next.legislation.find(x=>x.id===node!.parentId);}}
  for(const c of next.checklists){if(c.legislationIds.some(id=>!next.legislation.some(l=>l.id===id))||c.relatedIds.some(id=>!next.checklists.some(x=>x.id===id)))throw Error(`Broken checklist references on ${c.id}.`);}
  return next;
}
export function contentChanges(before: ContentVersion, after: ContentVersion) { return [...after.legislation.map(l=>({kind:"Legislation",id:l.id,title:l.title,domain:l.domain,change:!before.legislation.some(x=>x.id===l.id)?"New":JSON.stringify(before.legislation.find(x=>x.id===l.id))!==JSON.stringify(l)?"Amended":""})),...after.checklists.map(c=>({kind:"Checklist",id:c.id,title:c.title,domain:c.domain,change:!before.checklists.some(x=>x.id===c.id)?"New":JSON.stringify(before.checklists.find(x=>x.id===c.id))!==JSON.stringify(c)?"Amended":""}))].filter(x=>x.change); }
export function linkLawRecord(data: LawData, link: LawLink) { return data.links.some(l=>l.profileId===link.profileId&&l.checklistId===link.checklistId&&l.kind===link.kind&&l.recordId===link.recordId)?data:{...data,links:[...data.links,link]}; }
export function createLawIncident(source: LawSource, department: string, forms: FormBlueprint[], incidents: IncidentData) {
  if(!department) throw Error("Create a department in this profile site before raising an incident.");
  const type=incidents.types.find(t=>t.name==="Non Compliance"&&t.active);const form=forms.find(f=>f.id===type?.reportTemplate&&f.target==="Incident"&&f.status==="Published"&&f.incidentPurpose!=="Investigation"); if(!type||!form)throw Error("Activate the Non Compliance incident type and select a published Incident report form in Incident settings."); const i=newIncident(form);return recordHistory({...i,id:lawId("INC"),title:`Compliance gap · ${source.title}`,type:type.name,subtype:type.subtypes.find(x=>!(type.inactiveSubtypes||[]).includes(x))||"",department,assigned:["user-1"],people:[],draft:true,lawSource:source},"Draft created from Law; complete the report before submitting");
}
export function createLawAction(source: LawSource, department: string, title: string, owner: string, due: string): IncidentAction { if(!title.trim()||!department||!owner||!validDate(due))throw Error("Enter an action description, owner, department and valid due date.");return {id:lawId("ACT"),title:title.trim(),kind:"Corrective",incidents:[],owner,department,due,priority:"High",category:"Legal compliance",status:"Open",completion:"",reviewer:"",reviewDate:"",reviewNote:"",evidence:[],lawSource:source}; }
export function validateTask(task: LawTask, records: ImportRecords, profile: LegalProfile) { if(!task.title.trim()||!records.users.some(u=>u.id===task.ownerId)||departmentPath(records,task.departmentId).site?.id!==profile.siteId||!validDate(task.due))throw Error("Enter a task description, existing owner, department in the profile site and valid due date.");if(task.completed&&!task.completion.trim())throw Error("Enter a completion comment."); }

const initialLegislation: LegalPiece[] = [
  {id:"LEG-001",title:"Workplace safety framework",reference:"DEMO-HS-01",jurisdiction:"Ireland",domain:"Health & Safety",category:"General",level:"Primary",parentId:"",synopsis:"Sample framework for documenting responsibilities, workplace controls and periodic checks. This fictional summary is for presentation only.",sourceUrl:"https://www.irishstatutebook.ie/",keywords:["workplace","safety"],active:true},
  {id:"LEG-002",title:"Safe use of work equipment",reference:"DEMO-HS-02",jurisdiction:"Ireland",domain:"Health & Safety",category:"Machinery",level:"Secondary",parentId:"LEG-001",synopsis:"Illustrative requirements for equipment checks, guarding and competent operation.",sourceUrl:"https://www.irishstatutebook.ie/",keywords:["machinery","forklift","guarding"],active:true},
  {id:"LEG-003",title:"Workplace transport guidance",reference:"DEMO-HS-03",jurisdiction:"Ireland",domain:"Health & Safety",category:"Workplace transport",level:"Tertiary",parentId:"LEG-002",synopsis:"Illustrative guidance on traffic routes, pedestrian segregation and inspection records.",sourceUrl:"https://www.hsa.ie/",keywords:["transport","forklift","pedestrians"],active:true},
  {id:"LEG-004",title:"Environmental protection framework",reference:"DEMO-ENV-01",jurisdiction:"Ireland",domain:"Environment",category:"General",level:"Primary",parentId:"",synopsis:"Fictional framework for identifying environmental controls and keeping evidence of their operation.",sourceUrl:"https://www.irishstatutebook.ie/",keywords:["environment","emissions","waste"],active:true},
  {id:"LEG-005",title:"Waste management requirements",reference:"DEMO-ENV-02",jurisdiction:"Ireland",domain:"Environment",category:"Waste",level:"Secondary",parentId:"LEG-004",synopsis:"Sample controls for segregating waste, checking contractors and maintaining transfer records.",sourceUrl:"https://www.epa.ie/",keywords:["waste","contractor"],active:true},
  {id:"LEG-006",title:"Chemical storage and spill controls",reference:"DEMO-HS-04",jurisdiction:"Ireland",domain:"Health & Safety",category:"Chemical safety",level:"Secondary",parentId:"LEG-001",synopsis:"Illustrative requirements for chemical inventories, storage controls and response evidence.",sourceUrl:"https://www.hsa.ie/",keywords:["chemicals","spill","storage"],active:true},
];
const baseChecklist=(id:string,title:string,category:string,domain:LawDomain,requirements:string,legislationIds:string[],activityKeys:string[],keywords:string[]):LegalChecklist=>({id,title,category,domain,requirements,legislationIds,activityKeys,keywords,relatedIds:[],active:true});
const initialChecklists=[
  baseChecklist("CL-001","Workplace transport controls","Workplace transport","Health & Safety","Document the traffic plan, pedestrian routes, competent operators and periodic route inspections. Keep evidence of the controls being checked.",["LEG-002","LEG-003"],["Workplace transport"],["forklift","vehicles","pedestrians"]),
  baseChecklist("CL-002","Machine guarding and inspections","Machinery","Health & Safety","Identify machinery in scope, guarding arrangements and inspection responsibilities. Evaluate whether safeguards remain effective.",["LEG-001","LEG-002"],["Machinery"],["guarding","equipment"]),
  baseChecklist("CL-003","Chemical storage and spill readiness","Chemical safety","Health & Safety","Maintain a chemical inventory, describe storage and containment controls, and retain evidence of spill response readiness.",["LEG-006"],["Chemicals"],["chemical","spill","containment"]),
  baseChecklist("CL-004","Waste segregation and contractor records","Waste","Environment","Describe segregation arrangements, contractor checks and record retention. Evaluate these against the waste streams in your profile.",["LEG-004","LEG-005"],["Waste"],["waste","contractors"]),
  baseChecklist("CL-006","Responsibilities and emergency readiness","General","Health & Safety","Document relevant responsibilities, emergency arrangements and the evidence used to review them.",["LEG-001"],["Workplace operations"],["emergency","responsibility"]),
];
export function sampleLawPackage(): ContentPatch { return {version:"2026.Q4",released:"2026-10-01",summary:"Transport controls clarified; new emissions evidence checklist for profiles with air emissions.",legislation:[{...initialLegislation[2],synopsis:"Illustrative transport guidance now highlights review after layout changes and shift checks of pedestrian segregation."},{id:"LEG-007",title:"Workplace emissions evidence",reference:"DEMO-ENV-03",jurisdiction:"Ireland",domain:"Environment",category:"Emissions",level:"Secondary",parentId:"LEG-004",synopsis:"Sample recordkeeping and review requirements for workplace emissions controls.",sourceUrl:"https://www.epa.ie/",keywords:["emissions","monitoring"],active:true}],checklists:[{...initialChecklists[0],requirements:`${initialChecklists[0].requirements} Review the layout after changes and keep representative shift-check evidence.`},baseChecklist("CL-005","Air emissions monitoring evidence","Emissions","Environment","Describe the emission sources and monitoring arrangements; retain results and evidence of review against applicable conditions.",["LEG-004","LEG-007"],["Air emissions"],["emissions","monitoring"])]}; }
export function initialLawData(): LawData {
  const profile=(id:string,name:string,siteId:string,activities:string[],shared=true):LegalProfile=>({id,name,ownerId:"user-1",siteId,jurisdiction:"Ireland",activities,description:"Site activities and equipment used to identify potentially applicable demo requirements.",shared,active:true,showCompliance:true,version:"2026.Q3",history:[lawHistory("Legal profile created")]});
  const data:LawData={profiles:[profile("LP-001","Dublin · operational compliance","site-1",lawActivities),profile("LP-002","Cork · distribution compliance","site-2",["Workplace operations","Workplace transport","Waste"])],versions:[{version:"2026.Q3",released:"2026-07-01",summary:"Initial fictional compliance content for the Northstar presentation.",legislation:initialLegislation,checklists:initialChecklists}],evaluations:[],tasks:[],other:[],links:[],history:[]};
  const evaluation=(p:string,c:string,relevance:string,evaluation:string,score:number|null,departmentId:string):ChecklistEvaluation=>({...evaluationFor(data,p,c),relevance,evaluation,score,departmentId,reviewDate:"2026-12-15",evaluatedAt:today(),evidence:[{name:"Inspection checklist · sample.pdf"}],history:[lawHistory("Initial evaluation recorded")]});
  data.evaluations=[evaluation("LP-001","CL-001","Forklifts operate on the production floor; the EHS team owns the traffic plan.","Routes checked during the September inspection. Physical separation improvements remain open.",65,"dep-1"),evaluation("LP-001","CL-002","Maintenance inspects all fixed machinery and owns the guarding register.","Monthly inspection records reviewed; guards present on sampled equipment.",90,"dep-2"),{...evaluation("LP-001","CL-003","Chemicals and hydraulic oils are stored in the maintenance area.","",null,"dep-2"),reviewDate:"2026-09-25"},evaluation("LP-001","CL-004","Waste streams are segregated and collected by approved contractors.","Transfer records and contractor review sampled in September.",85,"dep-1"),evaluation("LP-002","CL-001","Forklift movements share the loading bay with pedestrians.","Near misses identified a segregation gap. A corrective action is still being verified.",45,"dep-3"),{...evaluation("LP-002","CL-006","","",null,"dep-3"),relevant:false,exclusionReason:"Emergency arrangements are assessed under the shared corporate programme for this demo."}];
  data.tasks=[{id:"LT-001",profileId:"LP-002",checklistId:"CL-001",title:"Verify pedestrian route controls across shifts",info:"Compare the traffic plan with observed routes and record the inspection evidence.",ownerId:"user-2",departmentId:"dep-3",due:"2026-09-29",priority:"High",completed:false,active:true,completion:"",history:[lawHistory("Compliance task created")]},{id:"LT-002",profileId:"LP-001",checklistId:"CL-003",title:"Review chemical containment inspection records",info:"Include the hydraulic oil spill investigation findings.",ownerId:"user-1",departmentId:"dep-2",due:addDays(today(),7),priority:"Medium",completed:false,active:true,completion:"",history:[lawHistory("Compliance task created")]}];
  data.links=[{id:"LL-001",profileId:"LP-002",checklistId:"CL-001",kind:"risk",recordId:"RA-1042",context:"Moving vehicles · pedestrian segregation"},{id:"LL-002",profileId:"LP-002",checklistId:"CL-001",kind:"incident",recordId:"INC-261",context:"Near miss at the loading bay"},{id:"LL-003",profileId:"LP-001",checklistId:"CL-002",kind:"risk",recordId:"RA-1038",context:"Machine guarding hazard"},{id:"LL-004",profileId:"LP-001",checklistId:"CL-003",kind:"incident",recordId:"INC-260",context:"Hydraulic oil spill evidence"}];return data;
}
