import type { FormBlueprint } from "./form-builder";
import type { ImportRecords } from "./bulk-import";

export type RiskMethod = "5x5" | "3x3" | "FMEA" | "Checklist";
export type RiskSettings = { method: RiskMethod; domain: "Health & Safety" | "Environment"; medium: number; high: number; critical: number; reviewMonths: number; notifyDays: number; siteIds: string[]; footnote: string };
export const defaultRiskSettings = (method: RiskMethod = "5x5"): RiskSettings => ({ method, domain: "Health & Safety", medium: method === "FMEA" ? 50 : method === "3x3" ? 3 : 5, high: method === "FMEA" ? 250 : method === "3x3" ? 6 : 10, critical: method === "FMEA" ? 500 : method === "3x3" ? 9 : 20, reviewMonths: 12, notifyDays: 14, siteIds: [], footnote: "Review controls whenever the activity or working conditions change." });
export type Answer = string | string[];
export type Hazard = { id: string; job: string; name: string; consequence: string; controls: string; recommendation: string; justification: string; likelihood: number; severity: number; detection: number; checklist: "Yes" | "No" | "Not applicable"; factors?: Record<string, number> };
export type Revision = { revision: number; date: string; action: string; comment: string; score: number; hazards: Hazard[] };
export type Assessment = { id: string; title: string; description: string; template: FormBlueprint; settings: RiskSettings; departmentId: string; ownerId: string; approverId: string; participants: string; itemType: string; item: string; mode: string; people: string; impact: string; workArea: string; reviewDate: string; status: "Draft" | "Awaiting approval" | "Approved" | "Archived"; revision: number; confidential: boolean; hazards: Hazard[]; answers: Record<string, Answer>; history: Revision[]; reviews: { date: string; comment: string; nextDate: string }[]; linkedIds: string[]; documents: string[]; attachments: string[]; legalTopics: string[] };
export type Objective = { id: string; title: string; domain: string; departmentId: string; ownerId: string; due: string; description: string; status: "Active" | "Completed" };
export type Target = { id: string; title: string; objectiveId: string; ownerId: string; due: string; baseline: number; current: number; goal: number; unit: string; direction: "Increase" | "Decrease"; status: "Active" | "Completed" };
export type Programme = { id: string; title: string; objectiveId: string; targetIds: string[]; departmentId: string; ownerId: string; start: string; due: string; budget: string; description: string; status: "Planned" | "Active" | "Completed" };
export type RiskTask = { id: string; title: string; info: string; kind: "RA" | "MP"; assessmentId: string; hazardId: string; programmeId: string; parentId: string; ownerId: string; created: string; due: string; status: "Open" | "In progress" | "Completed"; factor: string; original: number; target: number; completedDate: string; comments: string; actual: number };
export type RiskData = { assessments: Assessment[]; objectives: Objective[]; targets: Target[]; programmes: Programme[]; tasks: RiskTask[] };
export const today = () => new Date().toISOString().slice(0, 10);
export const plusMonths = (date: string, months: number) => { const value = new Date(`${date}T12:00:00`); value.setMonth(value.getMonth() + months); return value.toISOString().slice(0, 10); };
export const dateLabel = (date: string) => date ? new Date(`${date}T12:00:00`).toLocaleDateString("en-IE", { day: "numeric", month: "short", year: "numeric" }) : "Not set";
export const overdue = (date: string, status = "") => !!date && date < today() && !["Completed", "Archived"].includes(status);
export const newHazard = (): Hazard => ({ id: crypto.randomUUID(), job: "", name: "", consequence: "", controls: "", recommendation: "", justification: "", likelihood: 1, severity: 1, detection: 1, checklist: "Yes" });
export const fmeaFactors = (domain: string) => domain === "Environment" ? [
  ["Scale and spread", "severity"], ["Volumes of pollutants", "severity"], ["Duration of impact", "severity"], ["Toxicity", "severity"], ["Sensitivity of location", "severity"], ["Regulatory limits", "severity"],
  ["Activity frequency", "likelihood"], ["Abatement", "likelihood"], ["Containment", "likelihood"], ["Competency", "likelihood"], ["Control documentation", "likelihood"],
  ["Monitoring / inspections", "detection"], ["Incident history", "detection"], ["Equipment reliability", "detection"], ["Warning systems", "detection"], ["Management system audit", "detection"],
] : [
  ["Number of people at risk", "severity"], ["Sensitivity of people", "severity"], ["Duration of exposure", "severity"], ["Nature of hazard", "severity"], ["Regulatory limits", "severity"],
  ["Workplace design", "likelihood"], ["Engineering controls", "likelihood"], ["Administrative controls", "likelihood"], ["Competency", "likelihood"], ["Work equipment / PPE", "likelihood"],
  ["Monitoring / inspections", "detection"], ["Incident history", "detection"], ["Equipment reliability", "detection"], ["Warning systems", "detection"], ["Management system audit", "detection"],
];
export function hazardScore(h: Hazard, settings: RiskSettings) {
  if (settings.method === "Checklist") return h.checklist === "No" ? 1 : 0;
  const factor = (group: string, fallback: number) => { const names = fmeaFactors(settings.domain).filter(([, g]) => g === group).map(([n]) => n); return names.reduce((sum, name) => sum + (h.factors?.[name] ?? fallback), 0) / names.length; };
  return settings.method === "FMEA" ? Math.round(factor("severity", h.severity) * factor("likelihood", h.likelihood) * factor("detection", h.detection)) : h.likelihood * h.severity;
}
export const assessmentScore = (a: Assessment) => Math.max(0, ...a.hazards.map(h => hazardScore(h, a.settings)));
export function riskBand(score: number, settings: RiskSettings) { return settings.method === "Checklist" ? score ? "Action required" : "Satisfactory" : score >= settings.critical ? "Critical" : score >= settings.high ? "High" : score >= settings.medium ? "Medium" : "Low"; }
export function departmentPath(records: ImportRecords, id: string) { const department = records.departments.find(d => d.id === id); const location = records.locations.find(l => l.id === department?.parentId); const site = records.sites.find(s => s.id === location?.parentId); const unit = records.businessUnits.find(u => u.id === site?.parentId); return { department, location, site, unit }; }
export function targetProgress(t: Target) { if (t.goal === t.baseline) return t.current === t.goal ? 100 : 0; return Math.max(0, Math.min(100, Math.round((t.current - t.baseline) / (t.goal - t.baseline) * 100))); }
export function initialRiskData(forms: FormBlueprint[]): RiskData {
  const template = forms.find(f => f.id === "form-risk-express")!;
  const base = (id: string, title: string, departmentId: string, likelihood: number, severity: number, status: Assessment["status"], reviewDate: string): Assessment => ({ id, title, description: "Evaluate the activity with current controls in place and identify further improvements.", template: structuredClone(template), settings: defaultRiskSettings(), departmentId, ownerId: departmentId === "dep-3" ? "user-2" : "user-1", approverId: "user-1", participants: "Priya Shah", itemType: "Process or activity", item: title, mode: "Routine", people: "Employees, contractors", impact: "Direct", workArea: "", reviewDate, status, revision: status === "Approved" ? 1 : 0, confidential: false, hazards: [{ id: `haz-${id}`, job: title, name: id === "RA-1042" ? "Moving vehicles" : "Contact with moving equipment", consequence: "Serious injury", controls: "Trained operators, marked routes and scheduled inspections.", recommendation: "Improve physical segregation and verify control effectiveness.", justification: "Regular exposure remains despite existing procedures.", likelihood, severity, detection: 1, checklist: "Yes" }], answers: {}, history: [], reviews: [], linkedIds: [], documents: ["Emergency response procedure"], attachments: [], legalTopics: ["Workplace transport checklist (sample)"] });
  const assessments = [base("RA-1042", "Forklift movement in warehouse", "dep-3", 4, 5, "Approved", "2026-09-22"), base("RA-1038", "Machine guarding inspection", "dep-2", 3, 4, "Approved", "2026-12-15"), base("RA-1027", "Working at height", "dep-1", 3, 5, "Draft", "2027-01-20"), base("RA-1045", "Manual handling in dispatch", "dep-3", 2, 3, "Awaiting approval", "2027-03-01")];
  const env = base("RA-1047", "Solvent storage and transfer", "dep-2", 3, 4, "Approved", "2026-10-15"); env.template = structuredClone(forms.find(f => f.id === "form-risk-environment")!); env.settings = { ...defaultRiskSettings("3x3"), domain: "Environment" }; env.hazards[0] = { ...env.hazards[0], name: "Release to surface water", consequence: "Water contamination", likelihood: 2, severity: 3, controls: "Bunded storage, spill kits and operator training." }; assessments.push(env);
  const ladder = base("RA-LAD001", "Ladder LAD-001 · safe use assessment", "dep-2", 3, 4, "Approved", today());
  Object.assign(ladder, { itemType: "Equipment", item: "Ladder LAD-001", ownerId: "user-3", workArea: "Maintenance store", description: "Assess the planned use of this ladder and the controls required by company procedures.", documents: ["Ladder use procedure (sample)"], legalTopics: [] });
  ladder.hazards[0] = { ...ladder.hazards[0], name: "Fall from ladder", job: "Use of Ladder LAD-001", consequence: "Serious injury", controls: "Equipment suitability checks, trained users and checks before use.", recommendation: "Check ladder condition and suitability; consider a safer means of access where appropriate.", justification: "Potential harm remains when working at height." };
  assessments.push(ladder);
  assessments.filter(a => a.revision).forEach(a => a.history.push({ revision: 1, date: "2026-09-01", action: "Approved", comment: "Initial assessment approved by Alex Morgan.", score: assessmentScore(a), hazards: structuredClone(a.hazards) }));
  return { assessments, objectives: [{ id: "OBJ-001", title: "Improve safety across operational sites", domain: "Health & Safety", departmentId: "dep-1", ownerId: "user-1", due: "2026-12-31", description: "Reduce exposure to high risk activities through effective controls and planned reviews.", status: "Active" }, { id: "OBJ-002", title: "Reduce waste and resource consumption", domain: "Environment", departmentId: "dep-2", ownerId: "user-1", due: "2026-12-31", description: "Minimise waste generation and increase recycling.", status: "Active" }], targets: [{ id: "TGT-001", title: "Review all operational risk assessments", objectiveId: "OBJ-001", ownerId: "user-1", due: "2026-12-31", baseline: 60, current: 82, goal: 100, unit: "%", direction: "Increase", status: "Active" }, { id: "TGT-002", title: "Increase site recycling rate", objectiveId: "OBJ-002", ownerId: "user-1", due: "2026-12-31", baseline: 40, current: 58, goal: 75, unit: "%", direction: "Increase", status: "Active" }], programmes: [{ id: "MP-001", title: "Warehouse safety improvement", objectiveId: "OBJ-001", targetIds: ["TGT-001"], departmentId: "dep-3", ownerId: "user-2", start: "2026-09-01", due: "2026-12-15", budget: "€12,000", description: "Improve pedestrian segregation, vehicle controls and operator competency.", status: "Active" }, { id: "MP-002", title: "Waste minimisation programme", objectiveId: "OBJ-002", targetIds: ["TGT-002"], departmentId: "dep-2", ownerId: "user-1", start: "2026-09-15", due: "2026-12-31", budget: "€5,000", description: "Review packaging and engage suppliers on reusable materials.", status: "Planned" }], tasks: [{ id: "RT-208", title: "Install pedestrian barrier", info: "Separate the pedestrian route from forklift movements.", kind: "RA", assessmentId: "RA-1042", hazardId: "haz-RA-1042", programmeId: "MP-001", parentId: "", ownerId: "user-2", created: "2026-09-15", due: "2026-09-29", status: "In progress", factor: "likelihood", original: 4, target: 2, actual: 2, completedDate: "", comments: "" }, { id: "RT-209", title: "Obtain barrier quotations", info: "Compare three suppliers.", kind: "RA", assessmentId: "RA-1042", hazardId: "haz-RA-1042", programmeId: "MP-001", parentId: "RT-208", ownerId: "user-3", created: "2026-09-15", due: "2026-09-25", status: "Open", factor: "", original: 0, target: 0, actual: 0, completedDate: "", comments: "" }, { id: "MT-012", title: "Evaluate reusable packaging suppliers", info: "Document feasibility and costs.", kind: "MP", assessmentId: "", hazardId: "", programmeId: "MP-002", parentId: "", ownerId: "user-1", created: "2026-09-20", due: "2026-10-20", status: "Open", factor: "", original: 0, target: 0, actual: 0, completedDate: "", comments: "" }] };
}
