"""Build the standalone Law guide using the existing Risk guide theme and helpers."""
from pathlib import Path
import re
import runpy

ROOT = Path(__file__).resolve().parents[1]
helpers = runpy.run_path(str(ROOT / 'scripts' / 'build-user-guides.py'))
step, table, persona, people, checklist, build = [helpers[name] for name in ['step', 'table', 'persona', 'people', 'checklist', 'build']]

PROFILES = {
    'admin': {'label': 'Alex · Administrator', 'text': 'Alex prepares profiles and team access, installs the content library and publishes the Incident forms used for legal follow-up. In the demo Alex performs every role.', 'links': [['quick-demo', 'Practice run'], ['profiles', 'Profiles'], ['updates', 'Content updates']]},
    'coordinator': {'label': 'Sam · Compliance coordinator', 'text': 'Sam maintains the Cork profile, checks what applies, accepts updates for his profile and coordinates evaluations and outstanding work.', 'links': [['profiles', 'Profile scope'], ['evaluate', 'Evaluate requirements'], ['updates', 'Accept an update']]},
    'evaluator': {'label': 'Nora · EHS evaluator', 'text': 'Nora records why a requirement applies, reviews controls and evidence, identifies gaps and sets the next evaluation date within her Dublin scope.', 'links': [['evaluate', 'Evaluation'], ['evidence', 'Evidence'], ['connections', 'Risk and Incident links']]},
    'owner': {'label': 'Priya · Task / action owner', 'text': 'Priya carries out assigned work and records completion evidence. Law tasks and Incident corrective actions have different completion processes.', 'links': [['tasks', 'Law tasks'], ['connections', 'Corrective actions']]},
    'reviewer': {'label': 'Liam · Assurance reviewer', 'text': 'Liam reviews evaluation evidence and verifies corrective action effectiveness. This suggested independent review is an operating arrangement; Law has no separate approval button.', 'links': [['evaluate', 'Check the evaluation'], ['connections', 'Effectiveness'], ['reports', 'Reports']]},
    'designer': {'label': 'Sofia · Form designer', 'text': 'Sofia drafts Incident report forms for compliance incidents. Law checklists come from the legal content library and profile activities, rather than these Incident forms.', 'links': [['connections', 'Forms and generated incidents']]},
    'reader': {'label': 'Ethan · Site reader', 'text': 'Ethan reads the Cork register, outstanding work and reports. In the suggested model he does not change evaluations, profiles or the content library.', 'links': [['screens', 'Page map'], ['metrics', 'Read the dashboard'], ['reports', 'Reports']]},
}

team = people('Law', PROFILES, [
    persona('AM', 'Alex Morgan', 'Workspace administrator', 'Creates the workspace structure and roles, prepares profiles, installs content packages and publishes Incident forms.', 'All Northstar sites'),
    persona('SO', 'Sam O’Brien', 'Compliance coordinator', 'Maintains the Cork activity questionnaire, assigns evaluations, accepts profile updates and follows overdue work.', 'Cork · legal profile and Logistics'),
    persona('NH', 'Nora Hayes', 'EHS evaluator', 'Reviews Dublin controls and evidence, documents exclusions and identifies gaps. A proposed team member, not a current app user.', 'Dublin · assigned evaluations'),
    persona('PS', 'Priya Shah', 'Task / action owner', 'Completes assigned work and supplies evidence. The evaluator decides whether the checklist needs a new compliance assessment.', 'Dublin · assigned work'),
    persona('LC', 'Liam Connor', 'Assurance reviewer', 'Checks evidence and, when assigned in Incident, verifies action effectiveness. A proposed team member, not a current app user.', 'Dublin · assigned reviews'),
    persona('SR', 'Sofia Reed', 'Form designer', 'Designs draft Incident reports for legal non-compliance follow-up; Alex reviews and publishes them.', 'Incident report forms'),
    persona('EB', 'Ethan Byrne', 'Site reader', 'Reads his site’s register and reports, asks about gaps and monitors deadlines.', 'Cork · read access'),
], [
    ['Workspace administrator', 'Profiles, content packages and all demo records', 'All presentation workflow steps', 'Roles, structure, Incident template publication; all reports'],
    ['Compliance coordinator', 'Profile questionnaire; assigned evaluations and tasks', 'Accept content for owned profiles; review affected evaluations', 'Manage the site register; no tenant-wide access implied'],
    ['EHS evaluator', 'Assigned controls, evaluation, evidence and linked follow-up', 'Save evaluation; confirm a content review after checking evidence', 'Scoped register and evaluation history'],
    ['Task / action owner', 'Assigned work and its completion evidence', 'Complete a Law task; complete Incident action work', 'Cannot automatically change the checklist rating or close an incident'],
    ['Assurance reviewer', 'Review evidence; assigned Incident effectiveness review', 'Record action effectiveness in Incident; advise evaluator', 'Law has no separate evaluation approval stage in this prototype'],
    ['Form designer', 'Draft Incident templates and reusable questions', 'Alex publishes in this suggested arrangement', 'No Law content import or compliance decision implied'],
    ['Site reader', 'Read permitted records', 'None', 'Read scoped reports'],
], 'Sam could be a <strong>Law compliance coordinator at Cork</strong> and an <strong>Incident investigator at Cork</strong>. Priya could own tasks at Dublin without editing Cork’s profile. Give profile acceptance, content-library import and form publishing separate responsibilities in your proposed roles.')

# Use visible buttons for the learning routes: no native dropdown popup is needed.
choices = '<div class="learning-choices" role="group" aria-label="Choose your learning role">' + ''.join(
    f'<button type="button" class="button" data-learning-role="{key}" aria-pressed="{str(key == "admin").lower()}">{value["label"]}</button>'
    for key, value in PROFILES.items()) + '</div>'
team = re.sub(r'<label for="learning-role">.*?</select>', '<strong>What would you like to learn as?</strong>' + choices, team, flags=re.S)
globals_for_build = build.__globals__
script = globals_for_build['SCRIPT']
original = next(line for line in script.splitlines() if "document.getElementById('learning-role').addEventListener" in line)
replacement = original.replace("document.getElementById('learning-role').addEventListener('change', e => { const profile = profiles[e.target.value];", "document.querySelectorAll('[data-learning-role]').forEach(button => button.addEventListener('click', () => { document.querySelectorAll('[data-learning-role]').forEach(item => item.setAttribute('aria-pressed', String(item === button))); const profile = profiles[button.dataset.learningRole];")
replacement = replacement.rstrip()[:-3] + '}));'
globals_for_build['SCRIPT'] = script.replace(original, replacement)
globals_for_build['EXTRA_STYLE'] += '\n.learning-choices{display:flex;flex-wrap:wrap;gap:8px;margin:12px 0}.learning-choices .button{font-size:12px;text-align:left}.learning-choices [aria-pressed=true]{background:var(--ink);color:white;border-color:var(--ink)}.role-picker{display:block}.role-result{padding-top:8px}\n'

CHAPTERS = [
('start', 'Start here', '''<div class="grid two"><div class="card"><h3>Keep this guide beside the app</h3><ol><li>Use <strong>Open prototype</strong> above to open the app in another tab.</li><li>Enter invitation code <code>482916</code>.</li><li>Sign in with <code>admin@northstar.example</code> and <code>Demo123!</code>.</li><li>Expand <strong>Law</strong> and open <strong>Overview</strong>.</li></ol><p>Already signed in? Start at step 4.</p></div><div class="card"><h3>What you will learn</h3><p>Choose a site profile, understand what applies, record controls and evidence, organise follow-up and keep the register current.</p><p><a href="#quick-demo">Try the 15-minute Cork exercise →</a></p><p><a href="#people">Meet the example team →</a></p></div></div>
<div class="note warm"><strong>Presentation edition.</strong> Legal titles and requirement summaries in the app are fictional examples. They are not a current legal subscription or a legal compliance conclusion. App changes survive navigation in the same tab but reset on reload or sign-out. Evidence stores file names and references, not uploaded file contents; no notifications or legal feed run here.</div>'''),
('big-picture', 'The big picture', '''<p>A <strong>legal profile</strong> describes one site’s activities. It selects potentially applicable <strong>compliance checklists</strong> from a content library. You decide relevance, describe controls, evaluate evidence and follow up any gaps.</p>
<div class="journey" aria-label="Law workflow"><span>1. Define profile</span><b>→</b><span>2. Check relevance</span><b>→</b><span>3. Evaluate evidence</span><b>→</b><span>4. Follow up gaps</span><b>→</b><span>5. Review changes</span></div>''' + table(['Term', 'In plain language', 'Northstar example'], [
    ['Legal profile', 'A site, owner, jurisdiction and activity questionnaire. Its accepted content version identifies which library it uses.', 'Cork · distribution compliance'],
    ['Legislation register', 'Source topics and summaries, organised by register, category and hierarchy.', 'Workplace transport guidance, a fictional demo entry'],
    ['Compliance checklist', 'A practical topic combining requirements from one or more source entries.', 'Workplace transport controls'],
    ['Evaluation', 'Your explanation of applicability, controls, evidence and remaining gaps.', 'Check pedestrian routes and record what was reviewed'],
    ['Law task', 'A piece of compliance work with an owner and deadline.', 'Verify pedestrian route controls across shifts'],
    ['Incident action', 'Corrective or preventive work with a separate effectiveness review.', 'Improve loading bay segregation, then check the outcome'],
    ['Other requirement', 'A company, customer or voluntary commitment evaluated in the same way.', 'Corporate contractor induction standard'],
]) + '''<h3>Company structure and registers</h3><p class="path">Business unit → Site → Location → Department</p><p>Cork’s example is <strong>Operations → Cork Distribution → Warehouse → Logistics</strong>. Law uses its own <strong>Legal profile</strong> selector. When assigning evaluation work, the department choices belong to that profile’s site.</p><p>A register or domain here means <strong>Health &amp; Safety</strong> or <strong>Environment</strong>; it is a subject area, not a website address. Other company requirements have their own register.</p>'''),
('people', 'Who does what?', team),
('quick-demo', 'Your first practice run', '''<p>Use a fictional workplace transport example at Cork. Perform every step as Alex. In a real team, Sam coordinates the evaluation and a task owner verifies the controls on site.</p><div class="practice-summary"><span>About 15 minutes</span><span>Cork · distribution compliance</span><span>CL-001 · Workplace transport controls</span></div><p class="small">Start from the sample data before installing the quarterly update. If you have already changed it, your numbers may differ. Reload only when you deliberately want to discard the app tab’s changes.</p>''' +
    step(1, 'Choose Cork and open the topic', '<p>On <strong>Law → Overview</strong>, select <strong>Cork · distribution compliance</strong> from <strong>Legal profile</strong>. Open <strong>Compliance checklists</strong>, search “transport” and open <strong>Workplace transport controls</strong>. Read <strong>Requirements</strong>.</p>', 'The sample topic has a 45% self-assessment. Cork has two relevant checklists and one excluded checklist.') +
    step(2, 'See the connected evidence', '<p>Open <strong>Risk &amp; Incident</strong>. Open <strong>RA-1042 · Forklift movement in warehouse</strong>. Read the risk, then use its <strong>Legal compliance</strong> connection to return to this checklist. Open <strong>INC-261 · Near miss at loading bay</strong> and return the same way.</p>', 'Law opens the exact Risk or Incident record. Its return link opens Cork’s source checklist.') +
    step(3, 'Complete the sample Law task', '<p>Open the checklist’s <strong>Tasks</strong> tab, then <strong>LT-001 · Verify pedestrian route controls across shifts</strong>. In <strong>Completion comment</strong>, enter a fictitious practice result: “Demo exercise: checked both shifts; route markings are visible, but supervision at loading bay 2 needs follow-up.” Click <strong>Complete task</strong>.</p><p class="small">In real use, do the work before recording completion. This wording is only a presentation example.</p>', 'The task is Completed and keeps your comment. The checklist rating and evaluation are unchanged.') +
    step(4, 'Record an evaluation', '<p>Click <strong>Open source checklist</strong>, then <strong>Evaluation</strong>. Keep <strong>Relevant to this profile</strong> checked. Review or extend <strong>Why relevant / controls &amp; responsibility</strong>. In <strong>Evaluation of compliance / evidence</strong>, add: “Demo review of the task result and near-miss record: controls are documented; the loading bay supervision gap remains.”</p><p>Select <strong>Sam O’Brien</strong> as owner and <strong>Logistics</strong> as department, set a future <strong>Next evaluation review</strong> date, and click <strong>Save evaluation</strong>. Leave the sample score unchanged for this exercise.</p>', 'Both narratives, owner, department and review date are saved. Complete means the evaluation is recorded; it does not mean every gap is resolved or that the rating is 100%.') +
    step(5, 'Read the change history', '<p>Open <strong>History</strong> to see evaluation changes. Return to <strong>Overview</strong> and inspect the overdue task count. Open <strong>Reports → Compliance register</strong> for a tabular view.</p>', 'The task no longer contributes to the open overdue count. The self-assessment stays 45% unless you deliberately change it.') +
    '''<div class="note"><strong>Next practice:</strong> <a href="#updates">install the sample update and accept it for Cork</a>. The changed workplace transport evaluation needs an explicit content review. For a new compliance gap, <a href="#connections">create a draft incident or corrective action</a>.</div>'''),
('screens', 'Find the right page', table(['Law menu page', 'Use it to…', 'Try this first'], [
    ['Overview', 'Read the selected profile’s coverage, ratings and work needing attention.', 'Switch between Dublin and Cork'],
    ['Legal profiles', 'Maintain site activities, owner, sharing and dashboard visibility.', 'Edit Cork’s questionnaire'],
    ['Legislation', 'Search source summaries and follow their hierarchy and checklists.', 'Search transport'],
    ['Compliance checklists', 'Record relevance, evaluations, evidence and follow-up.', 'Open Workplace transport controls'],
    ['Tasks', 'Find, assign and complete individual pieces of Law work.', 'Search LT-001'],
    ['Changes & updates', 'Install content, accept it per profile and review affected evaluations.', 'Content library → Preview sample quarterly update'],
    ['Other requirements', 'Add company-specific commitments.', 'Create a contractor induction requirement'],
    ['Reports', 'Filter and export evaluations, tasks and linked records.', 'Compliance register'],
]) + '''<p>Start with the <strong>Legal profile</strong> selector: most Law pages show that profile’s data. Search by reference, title or keyword. Use register/category filters and the checklist status or relevance choices to narrow the list. Rows and pagination keep long lists manageable.</p><p>Inside a checklist use <strong>Requirements, Evaluation, Evidence, Tasks, Risk &amp; Incident and History</strong>. The small <strong>i</strong> button opens a short Law workflow explanation.</p><h3>Legislation hierarchy</h3><p><strong>Primary → Secondary → Tertiary</strong> displays a parent/child structure of source topics in the demo. Open a source entry to read its synopsis, parent and related topics, associated checklists and content history. Its portal link opens a general official source website; it does not verify that the fictional demo entry is an actual current statute.</p>'''),
('profiles', 'Create and maintain a profile', '''<p><strong>Suggested person:</strong> Alex sets it up; Sam owns the Cork questionnaire and keeps it current. A profile describes what potentially applies to its site, rather than granting access to that site.</p>''' +
    step(1, 'Create the profile', '<p>Open <strong>Law → Legal profiles → Create profile</strong>. Enter a name, choose an existing owner and site, and add a useful description. This presentation catalogue supports <strong>Ireland</strong>.</p><p>Example: “Dublin · maintenance activities”, Alex as owner, Dublin Plant as site.</p>', 'The profile has a named owner and one site. Create the company structure in Configuration first if the site is missing.') +
    step(2, 'Describe the activities', '<p>Under <strong>Activities, materials &amp; equipment</strong>, select the activities that actually describe the site: Workplace operations, Workplace transport, Machinery, Chemicals, Waste or Air emissions. Choose the workspace sharing / rating options and click <strong>Save profile &amp; generate scope</strong>.</p>', 'Matching checklists enter the profile. A new profile uses the latest installed content version; each evaluation still needs to be completed.') +
    step(3, 'Keep the questionnaire current', '<p>On its profile card use <strong>Edit profile</strong> when operations change. The existing profile’s site is fixed; use a new profile for a different site. Save the revised activity questionnaire.</p>', 'Newly matched topics become visible. A removed activity leaves its saved evaluation outside current scope; it does not erase that record.') +
    '''<h3>Profile card controls</h3>''' + table(['Control', 'Meaning'], [
    ['Open register', 'Select this profile and open its checklists.'],
    ['Share with workspace / Make private', 'Demonstrate the intended visibility arrangement. This admin-only prototype still allows Alex to operate every profile.'],
    ['Hide / Show compliance rating', 'Hide or show the self-assessment presentation without deleting saved ratings.'],
    ['Archive profile / Restore profile', 'Keep a profile for history instead of deleting it. Restore it before continuing normal checklist edits.'],
]) + '<div class="note"><strong>Two ways to remove a topic from today’s working view.</strong> Change activities when the site’s operations have changed. Use <strong>Not relevant</strong> with a reason when an individual generated checklist does not apply. Both preserve previous evaluation records.</div>'),
('evaluate', 'Record relevance and evaluation', '''<p><strong>Suggested people:</strong> Sam coordinates the Cork register; Nora evaluates Dublin topics; Liam checks the supporting evidence. There is no separate Law approval screen in this prototype.</p>''' +
    step(1, 'Read the requirement', '<p>Open a checklist’s <strong>Requirements</strong> tab. Read the requirement summary and associated source entries before recording your own findings.</p>', 'You understand which topic you are evaluating and which source content it belongs to.') +
    step(2, 'Explain applicability and controls', '<p>On <strong>Evaluation</strong>, keep <strong>Relevant to this profile</strong> checked if it applies. Fill <strong>Why relevant / controls &amp; responsibility</strong>: explain where it applies, what controls are in place and who maintains them.</p><p>Example: “Forklifts operate in the Cork warehouse. Marked routes and traffic rules are maintained by Logistics.”</p>', 'The first narrative explains the context and controls, rather than just saying “yes”.') +
    step(3, 'Evaluate evidence and assign responsibility', '<p>Fill <strong>Evaluation of compliance / evidence</strong>: describe what was checked, what it showed and any remaining gaps. Choose an existing <strong>Responsible owner</strong>, a department from the profile’s site and a future <strong>Next evaluation review</strong> date. Add evidence references in the next tab.</p>', 'The evaluation has a traceable basis and someone responsible for keeping it current.') +
    step(4, 'Save progress or the completed evaluation', '<p>Optionally use the <strong>Self-assessed compliance rating</strong> slider; <strong>Clear rating</strong> leaves it unassessed. Click <strong>Save evaluation</strong>. You can save partial notes and return later.</p>', 'Complete requires both narratives, owner, department and next review date, with no pending content-review flag. The score is optional and is a separate measure.') +
    '''<h3>When a checklist is not relevant</h3><ol><li>Uncheck <strong>Relevant to this profile</strong>.</li><li>Enter a specific <strong>Reason this is not relevant</strong>, explaining the decision.</li><li>Save. Find it later using the <strong>Not relevant</strong> filter.</li><li>Use <strong>Mark relevant again</strong> if the situation changes, then review the saved evaluation.</li></ol><p>Exclusion preserves notes, ratings, evidence, tasks and links. Excluded items do not contribute to the relevant checklist denominator.</p><div class="note warm"><strong>Outstanding work needs its own record.</strong> A written gap in the evaluation does not automatically create a task or incident. Add the follow-up explicitly in <strong>Tasks</strong> or <strong>Risk &amp; Incident</strong>.</div>'''),
('evidence', 'Keep evidence and company requirements', '''<p><strong>Suggested person:</strong> the evaluator maintains the evidence; task owners supply the supporting records.</p><h3>Evidence on a checklist</h3><ol><li>Open <strong>Evidence</strong> and add file references or a safe HTTP(S) document link using the evidence controls.</li><li>Save the evidence using the tab’s save control.</li><li>Describe the actual findings in <strong>Evaluation</strong>; a file reference alone does not complete the evaluation.</li></ol><p>Examples: “Cork route inspection.pdf”, a training register or a maintenance inspection record. This demo retains names and links only. The Document module is still a placeholder, so there is no working controlled-document upload or approval flow here.</p><h3>Add an other requirement</h3>''' +
    step(1, 'Describe the commitment', '<p>Open <strong>Law → Other requirements → Add requirement</strong>. Enter <strong>Requirement name</strong>, category, <strong>Requirement / commitment</strong> and optional comma-separated keywords.</p><p>Example: “Corporate contractor induction standard” — “Confirm induction and authorisation before work begins; retain the signed induction record.”</p>', 'The commitment belongs to the selected profile rather than the shared legislation catalogue.') +
    step(2, 'Evaluate it like the other topics', '<p>Click <strong>Save requirement</strong>. Its checklist opens. Record relevance, controls, evaluation, owner, department and next review; add evidence, tasks or cross-module links as needed.</p>', 'The company commitment uses the same checklist tabs and contributes to the relevant evaluation view when active and relevant.') +
    '<p>Use its list controls to edit or deactivate a commitment when appropriate. Keep history and previous evidence rather than treating deactivation as proof that the commitment was satisfied.</p>'),
('tasks', 'Assign and finish Law tasks', '''<p>A <strong>Law task</strong> is a piece of work linked to a checklist. A <strong>corrective action</strong> created in Incident includes a separate effectiveness process. Choose the record that fits the work.</p>''' +
    step(1, 'Create and assign the task', '<p>From a checklist’s <strong>Tasks</strong> tab add a task, or use <strong>Law → Tasks → Create task</strong>. Enter <strong>Task description</strong>, source checklist, responsible person, responsible department, target closure date, priority and additional information. Click <strong>Save task</strong>.</p>', 'The task has a deadline, an owner and a source checklist. The department must belong to the profile’s site.') +
    step(2, 'Find and do the work', '<p>Search the Tasks page and use owner, status and priority filters. Open a task to read the additional information. Use <strong>Edit task</strong> to change an open task, or <strong>Open source checklist</strong> for context.</p>', 'The owner understands both the work and the compliance topic it supports.') +
    step(3, 'Record completion', '<p>After doing the work, enter <strong>Completion comment</strong>, explaining what was done and the outcome. Click <strong>Complete task</strong>. A blank comment blocks completion.</p>', 'The completed task retains its comment and history. Its completion does not automatically change the checklist rating or clear a content-review flag.') +
    '''<p><strong>Archive task / Restore task</strong> keeps the record and history. Archive is different from completion: hiding a task does not prove the work was done. The demo’s daily checks and email reminders are not connected to these live Law records.</p>'''),
('connections', 'Connect Risk and Incident', '''<p>Legal evaluations can use Risk assessments and Incident records as supporting evidence or follow-up. The modules keep their own decisions: a link does not automatically approve a risk, close an incident or change compliance.</p><h3>Link an existing record</h3><ol><li>Open a checklist’s <strong>Risk &amp; Incident</strong> tab.</li><li>Under <strong>Link an existing record</strong>, choose <strong>Risk assessment</strong>, <strong>Incident</strong> or <strong>Corrective / preventive action</strong>.</li><li>Choose a record in this profile’s site.</li><li>Add a useful <strong>Hazard, aspect or link context</strong> and click <strong>Link record</strong>.</li><li>Open the connected record. Its <strong>Legal compliance</strong> panel returns to the exact profile checklist.</li></ol><p>Ordinary associations can be unlinked without deleting the record. A record created from Law retains its origin; its origin link is protected.</p><h3>Create a compliance incident</h3>''' +
    step(1, 'Create the draft from Law', '<p>Under <strong>Address a compliance gap</strong>, choose <strong>Department for new follow-up</strong>, then click <strong>Create compliance incident draft</strong>.</p>', 'A new Non Compliance incident appears in the connected list with its Law source. It is deliberately a Draft.') +
    step(2, 'Complete and submit in Incident', '<p>Open the generated incident. Edit its report, check the type, event details and assignments, answer required template questions, and submit through the normal Incident flow. Follow the <a href="incident-user-guide.html#record">Incident guide</a> for reporting and investigation.</p>', 'The published Incident report template and its version are preserved. Required answers must be supplied; creating a Law draft does not submit or close it.') +
    '''<div class="note"><strong>Where forms come from.</strong> Sofia drafts an <strong>Incident / Report</strong> form in <strong>Configuration → Form Builder</strong>; Alex publishes it and binds it to <strong>Non Compliance</strong> in Incident Settings. Without a compatible published form, draft creation is blocked with an explanation. Law checklists themselves come from the legal content library and profile questionnaire.</div><h3>Create a corrective action instead</h3><ol><li>Choose the follow-up department and click <strong>Create corrective action</strong>.</li><li>Enter the action description, owner and due date.</li><li>Click <strong>Save corrective action</strong>, then open its connected record.</li><li>In <strong>Incident → Actions</strong>, carry out the work and any child tasks, record completion and plan the effectiveness review.</li><li>The assigned reviewer checks effectiveness at the appropriate time. See the <a href="incident-user-guide.html#actions">Incident action guide</a>.</li></ol><p>A Law-origin corrective action can exist without a linked incident because its source is the compliance checklist. Follow-up actions keep that legal origin. The evaluator must separately revisit Law when the evidence changes.</p>'''),
('updates', 'Install content and review changes', '''<p><strong>Suggested people:</strong> Alex installs the shared content package; Sam accepts it for the Cork profile; the evaluator then checks affected controls and evidence. These are three distinct steps.</p><div class="journey" aria-label="Legal content update workflow"><span>1. Preview &amp; install library</span><b>→</b><span>2. Accept per profile</span><b>→</b><span>3. Review affected evaluations</span></div>''' +
    step(1, 'Preview the sample package', '<p>Open <strong>Law → Changes &amp; updates → Content library</strong>. Click <strong>Preview sample quarterly update</strong> to inspect the 2026.Q4 package. Alternatively use <strong>Download sample JSON</strong>, then the upload field. Review the New / Amended rows before installing.</p>', 'The preview includes amended workplace transport content and a new emissions topic. Previewing alone changes nothing.') +
    step(2, 'Install the library version', '<p>Click <strong>Install content into library</strong>.</p>', 'The installed library advances from 2026.Q3 to 2026.Q4. Existing profiles still use their own accepted versions; customer evaluations are preserved.') +
    step(3, 'Accept for Cork', '<p>Select <strong>Cork · distribution compliance</strong>. Open <strong>Profile updates</strong>, compare the profile version with the installed library, read the changes, and click <strong>Accept update into this profile</strong>.</p>', 'Cork uses 2026.Q4. Dublin remains at 2026.Q3 until accepted separately. Only matching activities add checklists: Cork does not gain the sample emissions checklist because it has no Air emissions activity.') +
    step(4, 'Re-evaluate the amended transport topic', '<p>Under <strong>Evaluations affected by accepted content</strong>, open <strong>Workplace transport controls</strong>. Read the current Requirements and content history. On <strong>Evaluation</strong>, update the controls, findings, evidence and review date as needed.</p><p>After checking them, tick <strong>I have reviewed controls and evidence against the current requirements</strong> and click <strong>Save evaluation</strong>. The completed evaluation fields must also be present.</p>', 'The content-review flag clears through this explicit review. Existing notes, evidence, tasks and Risk / Incident links remain available.') +
    '''<div class="note warm"><strong>Installation does not equal acceptance, and acceptance does not equal compliance.</strong> Changed associated legislation can require review even if the checklist text itself is unchanged. Unaffected evaluations keep their existing status. An overdue review date still needs attention after a content review.</div><p>Use <strong>History</strong> to distinguish customer evaluation changes from requirement content history. JSON uploads are previewed and validated, with a 2 MB limit. This is a sample manual workflow, not a connected provider feed or an automatic quarterly delivery service.</p>'''),
('metrics', 'Understand statuses and dashboard numbers', table(['What you see', 'What it means'], [
    ['Relevant checklists', 'Active, currently scoped topics not excluded with a reason. Other active company requirements are included.'],
    ['Evaluations complete', 'Both narratives are recorded, with no pending content-review flag. This measures recording progress, not legal compliance.'],
    ['Self-assessed compliance', 'Average of saved scores on relevant, in-scope topics only. The rated-count coverage tells you how many contributed. Unscored topics are not treated as 100%.'],
    ['Not assessed', 'No optional rating has been recorded. It can coexist with a completed written evaluation.'],
    ['Overdue tasks', 'Open active Law tasks with a target date before today. Completed or archived tasks are excluded.'],
    ['Reviews needing attention', 'Topics flagged for content review or past their next evaluation date. Hiding ratings changes the Overview emphasis, while preserving scores.'],
]) + '''<h3>Checklist status</h3>''' + table(['Status', 'Your next move'], [
    ['Not started', 'Start the applicability / controls and evidence narratives.'],
    ['Partial', 'Finish the missing narrative and required responsibility / review details.'],
    ['Complete', 'Keep the evidence current; follow up any recorded gaps and review at the next date.'],
    ['Review required', 'Read changed requirements, update evidence and explicitly confirm the content review.'],
    ['Not relevant', 'Keep a defensible reason; mark relevant again if circumstances change.'],
    ['Outside current profile', 'The activity questionnaire no longer brings this topic into scope. Historical records remain available in the filtered view.'],
]) + '''<p>Sample Cork starts at <strong>45%</strong> from one rated topic out of two relevant topics; the unassessed waste topic is not included in the average. Dublin starts at <strong>80%</strong> from three rated topics out of five. Score colours are red below 50, amber 50–79 and green 80–100; they visualise the user’s self-assessment rather than certify compliance.</p>'''),
('reports', 'Read and share reports', '''<p><strong>Suggested person:</strong> Ethan reads Cork’s reports; Sam checks the outstanding work; Alex reviews the wider presentation.</p><ol><li>Open <strong>Law → Reports</strong>.</li><li>Choose the <strong>Legal profile</strong> and report tab.</li><li>Use search and register/category filters. For tasks, use the owner, status and priority controls and optional <strong>Due from / Due to</strong> dates.</li><li>Open a source checklist or linked record for detail.</li><li>Use <strong>Export CSV</strong> or <strong>Print / save PDF</strong> in the browser.</li></ol>''' + table(['Report tab', 'Use it for…'], [
    ['Compliance register', 'Checklist status, controls, evaluation, self-assessment and next review. Read rated coverage on Overview before presenting an average.'],
    ['Task tracking', 'Responsibilities, target dates, status and the checklist supported by each task. Dates filter due dates, not event dates.'],
    ['Risk & Incident links', 'Traceability between a checklist and its connected assessments, incidents and actions. A linked record is not automatically closed or effective.'],
]) + '''<p>CSV uses the current selection and filters. Browser PDF output is a print view, not a certified compliance report. Exporting does not save the app’s in-memory edits back into a database.</p><div class="guide-links"><a href="risk-user-guide.html">Risk guide →</a><a href="incident-user-guide.html">Incident guide →</a><a href="audit-user-guide.html">Audit guide →</a></div>'''),
('help', 'Questions and practice checklist', '''<details><summary>Why do Dublin and Cork show different topics?</summary><p>Each profile uses its own site, activity questionnaire, accepted content version and exclusions. A library update can be accepted for one profile while another keeps the old version.</p></details>
<details><summary>Why is there no update to accept?</summary><p>The initial profiles already use the latest installed library, 2026.Q3. Preview and install the sample 2026.Q4 package in Content library first, then accept it separately for the selected profile.</p></details>
<details><summary>Why is an evaluation complete while its score is low?</summary><p>Complete means the evaluation is recorded. Its evidence may describe gaps. The optional score measures a separate self-assessment; neither completion nor a high rating establishes legal compliance.</p></details>
<details><summary>Why did finishing a task leave the score and review flag unchanged?</summary><p>Task completion records work. The evaluator must review the new evidence and make an explicit evaluation decision. A content-review flag also requires its confirmation checkbox.</p></details>
<details><summary>Why can’t I save a completed evaluation?</summary><p>Check both narratives, an existing owner, a department in this profile’s site and a valid next review date. A Not relevant decision requires a reason. Partial notes can be saved before completing the evaluation.</p></details>
<details><summary>Why does an excluded topic seem to have disappeared?</summary><p>The normal working filter shows relevant topics. Switch to Not relevant or the appropriate wider relevance view. An activity removal appears under Outside current profile. Saved notes, evidence and links are retained.</p></details>
<details><summary>Why can’t I find a record to link?</summary><p>The selection is limited to this profile’s site and the chosen record type. Check the selected profile and the record’s department/site. Linking does not create broader access rights.</p></details>
<details><summary>Why is my new incident still a draft?</summary><p>Law creates a Non Compliance draft with the published Incident report template. Complete its mandatory answers and event details, then submit in Incident. Do not create another draft just because the first is not submitted.</p></details>
<details><summary>Who approves a Law evaluation?</summary><p>This prototype saves an evaluation and supports explicit content review; it has no separate approval stage. Liam’s independent assurance role is a proposed operating process. Incident corrective action effectiveness has its own reviewer step.</p></details>
<details><summary>Why did my changes vanish after refresh?</summary><p>App records are stored only in that tab’s memory. Navigation preserves them; reload and sign-out reset them. The guide’s practice ticks are saved separately in browser storage when available.</p></details>
<details><summary>Do the fictitious roles control access now?</summary><p>No. Use only the admin login for this presentation. The responsibility table helps design future scoped roles; confidentiality and permission enforcement remain production work.</p></details>''' + checklist([
    'I selected Cork and found Workplace transport controls.',
    'I followed RA-1042 and INC-261 and returned to the exact checklist.',
    'I completed the sample Law task with a practice comment.',
    'I recorded controls, evidence, owner, department and the next review.',
    'I can explain Complete versus self-assessed compliance.',
    'I know how to exclude a topic with a reason and restore it.',
    'I can distinguish a Law task from an Incident corrective action.',
    'I installed the sample library and accepted it only for Cork.',
    'I explicitly reviewed the amended workplace transport evaluation.',
    'I understand the proposed team roles and admin-only access.',
]))]

if __name__ == '__main__':
    build('law', CHAPTERS, PROFILES, 'From obligation<br><em>to evidence.</em>', 'Understand what applies to each site, record how your team responds, follow the gaps and keep the evidence current. Learn with one clear example and a fictitious Northstar team.', '15-minute')
