"""Build standalone Incident, Audit and Law guides using the existing Risk guide theme.

Run from any directory: python scripts/build-user-guides.py
The generated files have no external dependencies and also work via file://.
"""
from pathlib import Path
import html
import json
import re

ROOT = Path(__file__).resolve().parents[1]
RISK = (ROOT / "public/risk-user-guide.html").read_text(encoding="utf-8")
STYLE = re.search(r"<style>(.*?)</style>", RISK, re.S).group(1)
SCRIPT = re.search(r"<script>(.*?)</script>", RISK, re.S).group(1)
EXTRA_STYLE = """
.journey{display:flex;gap:8px;flex-wrap:wrap;margin:20px 0}.journey span{padding:10px 13px;border:1px solid var(--line);border-radius:10px;background:white;font-size:13px;font-weight:700}.journey b{align-self:center;color:var(--blue)}
.guide-links{display:flex;flex-wrap:wrap;gap:14px;margin:22px 0}.guide-links a{font-size:13px;font-weight:700}.persona .scope{display:block;margin-top:10px;font-size:12px;color:var(--muted)}
.role-result{min-height:78px}.practice-summary{display:flex;gap:12px;flex-wrap:wrap;margin-top:22px}.practice-summary span{border:1px solid var(--line);padding:8px 12px;border-radius:8px;background:white;font-size:12px}.grid.three{grid-template-columns:repeat(3,minmax(0,1fr))}.persona h3{margin-top:14px}.persona p{font-size:13px}.persona{min-width:0}.persona:last-child{align-self:start}.step>div{min-width:0}.search-area label{display:block;margin-bottom:7px}.grid{min-width:0}
@media(max-width:1100px){.grid.three{grid-template-columns:repeat(2,minmax(0,1fr))}}
@media(max-width:800px){.grid.three{grid-template-columns:1fr}}
@media print{.guide-links,.role-card{display:none}.journey span{padding:6px}.step{break-inside:avoid}.grid.three{display:block}}
"""


def step(n, title, body, expected):
    return f'<div class="step"><span class="step-index">{n}</span><div><h3>{title}</h3>{body}<div class="expected"><strong>What you should see:</strong> {expected}</div></div></div>'


def table(heads, rows):
    return '<div class="table-wrap"><table><thead><tr>' + ''.join(f'<th scope="col">{x}</th>' for x in heads) + '</tr></thead><tbody>' + ''.join('<tr>' + ''.join(f'<td>{x}</td>' for x in row) + '</tr>' for row in rows) + '</tbody></table></div>'


def persona(initials, name, role, body, scope):
    return f'<article class="card persona"><div class="avatar">{initials}</div><h3>{name}</h3><span class="tag">{role}</span><p>{body}</p><span class="scope">Suggested scope: {scope}</span></article>'


def people(module, profiles, personas, rows, example):
    options = ''.join(f'<option value="{key}">{value["label"]}</option>' for key, value in profiles.items())
    return f'''<p>This is a suggested way to organise a real team. These responsibilities are <strong>illustrative</strong>; they are not permission restrictions in the current prototype.</p>
<div class="grid three">{''.join(personas)}</div>
<div class="note"><strong>For this presentation, play every role as Alex.</strong> Sign in with <code>admin@northstar.example</code>. The other names below explain the hand-offs; they are not additional working demo logins.</div>
<h3>A simple responsibility map</h3><p>“Assigned” means the person handles a particular record. “Within scope” means the role is limited to its business unit, site, location or department. A record assignment should not give someone unrestricted access to the whole company.</p>
{table(['Suggested role', 'Create / edit', 'Confirm / close', 'Configuration / reporting'], rows)}
<div class="note warm"><strong>One person can have more than one role.</strong> {example} Use <strong>Configuration → Roles & permissions</strong> to demonstrate the role and scope assignments. In a production system, the permissions and confidentiality rules would need to be enforced.</div>
<div class="card role-card"><div class="role-picker"><label for="learning-role"><strong>What would you like to learn as?</strong></label><select id="learning-role">{options}</select></div><div class="role-result" id="role-result" aria-live="polite"><p>{profiles['admin']['text']}</p>{' · '.join(f'<a href="#{i}">{label}</a>' for i, label in profiles['admin']['links'])}</div></div>'''


def checklist(items):
    return '<div class="card"><h3>Your practice checklist</h3><p class="small">Your ticks are saved in this browser when storage is available. This checklist does not change any app records.</p><ul class="checklist">' + ''.join(f'<li><label><input type="checkbox" data-check="item-{n}"><span>{text}</span></label></li>' for n, text in enumerate(items, 1)) + '</ul><div class="progress" aria-hidden="true"><div id="check-progress" style="width:0"></div></div><p id="check-count" aria-live="polite"></p><button class="button" id="reset-checklist" type="button">Reset checklist</button></div>'


INCIDENT_PROFILES = {
    'admin': {'label': 'Alex · Workspace administrator', 'text': 'Alex prepares the forms and type rules, oversees the process and demonstrates every role using the admin login.', 'links': [['quick-demo', 'Practice run'], ['templates', 'Templates and settings'], ['reports', 'Reports']]},
    'reporter': {'label': 'Jordan · Incident reporter', 'text': 'Jordan records what happened, the people involved and the immediate response. The investigator then follows up.', 'links': [['record', 'Record an incident'], ['screens', 'Find a record']]},
    'investigator': {'label': 'Sam · Investigator', 'text': 'Sam gathers evidence, records the causes and decides what corrective work is needed within the assigned site.', 'links': [['investigate', 'Investigate'], ['actions', 'Raise actions'], ['closure', 'Close the incident']]},
    'owner': {'label': 'Priya · Action / task owner', 'text': 'Priya carries out the assigned work and records what was done. Completion is followed by an effectiveness review.', 'links': [['actions', 'Complete tasks and actions'], ['closure', 'Effectiveness check']]},
    'reviewer': {'label': 'Liam · Effectiveness reviewer', 'text': 'Liam checks whether the corrective work actually solved the problem, records the evidence and requests a follow-up if needed.', 'links': [['quick-demo', 'Try the review'], ['closure', 'Effectiveness and closure']]},
    'designer': {'label': 'Sofia · Form designer', 'text': 'Sofia designs the report and investigation forms. In this suggested arrangement Alex reviews and publishes them.', 'links': [['templates', 'Prepare the forms']]},
    'reader': {'label': 'Ethan · Site manager / reader', 'text': 'Ethan monitors overdue work and trends for his site without changing incident records.', 'links': [['screens', 'Page map'], ['trends', 'Trends'], ['reports', 'Reports']]},
}

INCIDENT = [
('start', 'Start here', '''<div class="grid two"><div class="card"><h3>Use the guide beside the app</h3><ol><li>Open the prototype in another tab.</li><li>Enter invitation code <code>482916</code>.</li><li>Sign in as <code>admin@northstar.example</code>, password <code>Demo123!</code>.</li><li>Expand <strong>Incident</strong> in the workspace menu.</li></ol><p>If you are already on the home page, start at step 4.</p></div><div class="card"><h3>What you will learn</h3><p>Report an event, investigate the causes, assign corrective work, check that it worked and close the record.</p><p><a href="#quick-demo">Start the 10-minute practice run →</a></p><p><a href="#people">Meet the example team →</a></p></div></div>
<div class="note warm"><strong>Demo behaviour:</strong> records live in this app tab's memory. Navigation keeps your changes, but reloading or signing out starts again with the sample data. These guides can be read independently and printed. Evidence keeps file names and links; notifications and external reports are not actually sent.</div>'''),
('big-picture', 'The big picture', '''<p>An <strong>incident</strong> is the event. An <strong>investigation</strong> explains why it happened. An <strong>action</strong> fixes or prevents a problem. A <strong>task</strong> is one piece of the work needed to finish that action.</p>
<div class="journey" aria-label="Incident workflow"><span>1. Report</span><b>→</b><span>2. Investigate</span><b>→</b><span>3. Act</span><b>→</b><span>4. Verify effectiveness</span><b>→</b><span>5. Close</span></div>
<div class="grid two"><div class="card"><h3>Corrective action</h3><p>Fix a problem that has happened. Example: install signs after an inspection found an unmarked pedestrian route.</p></div><div class="card"><h3>Preventive action</h3><p>Reduce the chance of a future problem. Example: refresh loading-bay training after several similar near misses.</p></div></div>
<div class="note"><strong>Finished work is not the same as a solved problem.</strong> An action goes from <strong>Open / In progress → Awaiting effectiveness → Effective or Ineffective</strong>. An incident can close only when its required investigation and follow-up conditions are satisfied.</div>
<h3>How the company structure fits</h3><p class="path">Business unit → Site → Location → Department</p><p>Example: <strong>Operations → Cork Distribution → Warehouse → Logistics</strong>. Choosing the department identifies its parent location and site. Assigned people and suggested roles should operate within this structure.</p>
<h3>Audit findings can start this workflow too</h3><p>A confirmed major audit non-conformance creates an incident. A minor non-conformance creates a corrective action; an opportunity for improvement creates a preventive action. Use <strong>Open source audit</strong> on an originating record to return to the audit.</p>'''),
('people', 'Who does what?', people('Incident', INCIDENT_PROFILES, [
    persona('AM','Alex Morgan','Workspace administrator','Sets up forms, incident types, cause lists and team access. Oversees the demo.','All Northstar sites'),
    persona('JK','Jordan Kelly','Incident reporter','Reports a near miss promptly, describes the event and records witnesses and immediate response.','Cork · Logistics'),
    persona('SO','Sam O’Brien','Investigator','Gathers facts, identifies causes, completes the investigation and coordinates corrective work.','Cork · assigned incidents'),
    persona('PS','Priya Shah','Action / task owner','Finishes the assigned work and provides completion comments and evidence.','Assigned work at Dublin'),
    persona('LC','Liam Connor','Effectiveness reviewer','Checks the outcome against evidence. In this suggested model a different person reviews the owner’s work.','Dublin · assigned reviews'),
    persona('SR','Sofia Reed','Form designer','Creates draft questions and reusable fields. Alex publishes the finished templates.','Incident forms'),
    persona('EB','Ethan Byrne','Site manager / reader','Reads permitted incidents, trends and reports, and follows overdue work.','Cork · non-confidential records'),
], [
    ['Reporter','Create report; edit permitted draft','Submit report','No workspace settings'],
    ['Investigator','Assigned investigation; raise / link actions','Complete investigation; close when ready','Read evidence and history within scope'],
    ['Action / task owner','Assigned actions and tasks','Complete work with a comment','No automatic right to change the source incident'],
    ['Effectiveness reviewer','Review evidence on assigned actions','Record Effective / Ineffective','A suggested separate reviewer'],
    ['Form designer','Create / edit draft templates','Publishing reserved for Alex in this example','No incident closure rights implied'],
    ['Site reader','Read permitted records only','None','Read scoped reports'],
    ['Workspace administrator','All records for the demonstration','All demo workflow steps','Types, forms, roles and reporting'],
], 'Sam could be an <strong>Incident investigator at Cork</strong> and a <strong>Lead auditor at Dublin</strong>. Neither assignment should automatically give him access to Corporate records. Confidential incident access needs a separate explicit permission.')),
('quick-demo', 'Your first practice run', '''<p>Start with a nearly finished sample incident. You will verify an action and then close its incident. Play the reviewer and investigator as Alex; the guide explains who would normally perform each step.</p><div class="practice-summary"><span>About 10 minutes</span><span>INC-252 · Missing pedestrian signage</span><span>ACT-090 · Install pedestrian warning signs</span></div>''' +
    step(1,'Find the incident','<p>Go to <strong>Incident → Incidents</strong>. Search for <code>INC-252</code> and open <strong>Missing pedestrian signage</strong>.</p>','The investigation is completed. Its linked action still needs an effectiveness decision.') +
    step(2,'Read the work that was done','<p>Open the <strong>Actions</strong> tab, then <strong>ACT-090 · Install pedestrian warning signs</strong>. Read the completion comment and completed task.</p>','The action is <strong>Awaiting effectiveness</strong>. Alex is its sample reviewer; the review date is 30 September 2026.') +
    step(3,'Verify effectiveness','<p>In <strong>Verify effectiveness</strong>, choose <strong>Effective</strong>. Enter a <strong>Review evidence / comment</strong>, for example: “Route inspected during a shift change; the new signs are visible and pedestrians use the marked route.” Click <strong>Record effectiveness</strong>.</p><p class="small">Normal role: reviewer. In the demo, use Alex. The button becomes available on the planned review date.</p>','The action shows <strong>Effective</strong> and keeps your review comment.') +
    step(4,'Close the incident','<p>Use the associated <strong>INC-252</strong> link to return to the incident. Find its closure panel, enter a <strong>Closure note</strong>, such as “Investigation complete and signage action verified effective.” Click <strong>Close incident</strong>.</p><p class="small">Normal role: authorised investigator / incident manager.</p>','The incident shows <strong>Closed</strong>. Its <strong>History</strong> tab records the closure.') +
    '''<div class="note"><strong>Optional second exercise:</strong> open <strong>ACT-093 · Refresh loading bay markings</strong>. Complete its task <strong>IT-031 · Agree pedestrian route with logistics team</strong>, then complete the action and plan its effectiveness review. This action is shared by <strong>INC-261</strong> and <strong>INC-245</strong>; its outcome affects both.</div>'''),
('screens', 'Find the right page', table(['Incident menu page','Use it when you want to…','A good first move'],[
    ['Overview','See open incidents, overdue work and reviews','Open a record that needs attention'],
    ['Incidents','Search, report or read an event','Search INC-252 or create a new report'],
    ['Investigations','Find cases needing investigation','Open a case and its investigation'],
    ['Actions','Manage corrective and preventive work','Search ACT-090 or create an action'],
    ['Tasks','Find individual pieces of assigned work','Open IT-031 and its parent action'],
    ['Trends & prevention','Find repeated events and plan prevention','Choose criteria and preview matches'],
    ['Reports','Summarise events, causes, lost days and follow-up','Choose report and date range'],
    ['Settings','Maintain types, causes, reportees and export layout','Inspect Near Miss type settings'],
]) + '''<p>Open an incident to use its <strong>Report, Investigation, Actions, Evidence and History</strong> tabs. Use search first; expand <strong>More filters</strong> to narrow a large register. The small information icon opens a short explanation of the current page.</p>'''),
('templates', 'Prepare forms and settings', '''<p><strong>Suggested people:</strong> Sofia drafts the form; Alex reviews, publishes and selects the type rules. Forms come from the shared <strong>Form Builder</strong>.</p>''' +
    step(1,'Create the right kind of form','<p>Open <strong>Configuration → Form Builder → Create form</strong>. Enter a name, choose the <strong>Incident</strong> module, then choose <strong>Report</strong> or <strong>Investigation</strong> as the purpose. Keep the system fields and add the custom questions you need.</p>','A report form captures the event; an investigation form captures the follow-up. They are separate template purposes.') +
    step(2,'Add or reuse questions','<p>Drag a component into the form, or use its add control. Configure its label, help text, required setting and options. Use the Components search to reuse an existing field; selecting it adds a copy at the end. Reorder questions to match the way people work.</p><p>Examples: report question “Was the area made safe?”; investigation question “How was the root cause verified?”. Check any site-specific visibility rules.</p>','The form preview shows your questions in the intended order. Required questions must be answered when submitting or completing the relevant workflow.') +
    step(3,'Publish and connect the forms','<p>Publish the finished form. Open <strong>Incident → Settings → Incident types</strong>, select a type and choose its published report and investigation templates. Review subtypes, assignment rules, investigation requirements, confidentiality, evidence and investigation target days. Save the type settings.</p>','Published compatible forms can be selected for new work. Draft forms cannot.') +
    '''<div class="note"><strong>Existing records keep their template snapshot.</strong> Publishing a revised form changes future records; it does not rewrite the questions or answers on incidents already created.</div>
<h3>The other Settings tabs</h3>''' + table(['Tab','What Alex maintains'],[
    ['Causes','Reusable causes grouped by Equipment, Materials, Methods, People and Workplace. Deactivate unused choices rather than changing historical records.'],
    ['Reportees','Internal or external destinations used to describe who should be informed. The demo does not send reports or notifications.'],
    ['Export layout','The CSV columns, their order and available custom report fields.'],
]) + '<p>Type names are predefined in this prototype. Activate or deactivate the relevant subtypes and choices; historical values remain readable.</p>'),
('record', 'Record an incident', '''<p><strong>Suggested person:</strong> Jordan, the reporter. Record the facts available now; the investigation supplies the later analysis.</p>''' +
    step(1,'Start the report','<p>On <strong>Incident → Incidents</strong>, create a new incident. Choose the published report template and the <strong>type / subtype</strong>, then enter a clear title, severity and the event date and time.</p><p>Example title: “Near miss between forklift and pedestrian at loading bay”. Use the time the event happened, rather than the time you entered the record.</p>','The template’s custom questions appear alongside the standard incident fields.') +
    step(2,'Describe where and who','<p>Choose <strong>Department</strong>, describe the precise location and shift, and assign an investigator. Use <strong>Add person</strong> for each witness or injured person; select Employee / Third party and their involvement. Add injury information where relevant.</p><p>Example: Logistics at Cork, loading bay 2, Sam as investigator, Jordan as witness.</p>','The site follows the selected department. Investigator requirements follow the incident type’s single or multiple assignment rule.') +
    step(3,'Describe the event and immediate response','<p>Enter what happened and what was done immediately. Complete required custom questions and record appropriate evidence names or links. Review confidentiality and reportee information where shown.</p><p>Example immediate response: “Vehicle stopped and loading bay isolated while the route was checked.”</p>','The report separates the event description from later root-cause findings.') +
    step(4,'Save a draft or submit','<p>Choose <strong>Save draft</strong> if you still need information. A named draft can be incomplete. Choose <strong>Submit incident</strong> when the required report fields are complete.</p>','A draft remains <strong>Draft</strong>. A submitted report enters the active workflow; validation explains any missing required information.') +
    '''<div class="note warm"><strong>Confidentiality in this presentation:</strong> the flag demonstrates how a sensitive report could be marked. It does not restrict Alex’s access or implement production privacy controls.</div>'''),
('investigate', 'Investigate the causes', '''<p><strong>Suggested person:</strong> Sam, the assigned investigator. Use the incident record’s <strong>Investigation</strong> tab or the Investigations register.</p>''' +
    step(1,'Open the investigation','<p>Choose <strong>Start investigation</strong> or <strong>Open investigation</strong>. Select the published investigation form and complete its required questions.</p>','The investigation is linked to this incident and keeps a snapshot of its selected template.') +
    step(2,'Record findings and causes','<p>Explain the facts, investigation findings and root cause. Select relevant causes from the grouped list. Record applicable safety hazards or environmental aspects and impacts. Add evidence references and identify whether further action is required.</p><p>Example: “The pedestrian route was removed during a layout change and the change review did not include traffic segregation.”</p>','The record explains why the event happened and what follow-up is needed.') +
    step(3,'Record absence or impact if relevant','<p>Use <strong>Add absence</strong> for lost-time or restricted-duty periods. Enter the start and end dates and the correct kind. Record environmental duration, unit or impact details only where relevant.</p>','Reports can distinguish lost-time absence from restricted duties. Lost days are inclusive calendar days, not working days.') +
    step(4,'Save or finish','<p>Use <strong>Save progress</strong> while collecting evidence. When the required findings, causes, custom questions and closing information are complete, choose <strong>Complete investigation</strong>. If action is required, raise or link it from the incident’s Actions tab.</p>','The investigation becomes <strong>Completed</strong>. Completing it does not automatically complete actions or close the incident.') +
    '<p>A reopened investigation returns the incident to an unfinished investigation state. The incident cannot close until its required investigation is complete again.</p>'),
('actions', 'Create and complete the work', '''<p><strong>Suggested people:</strong> Sam defines the work; Priya or another assigned owner carries it out. An action can contain several tasks, or no tasks if its work can be recorded directly.</p>''' +
    step(1,'Raise or link an action','<p>On an incident’s <strong>Actions</strong> tab choose <strong>Raise action</strong>. Enter a clear description, Corrective / Preventive kind, department, owner, due date, priority and category. Choose <strong>Save action</strong>.</p><p>If an existing action addresses this incident too, select it and use <strong>Link action</strong> instead of making duplicate work.</p>','The action appears against the incident. A shared action can be associated with more than one incident.') +
    step(2,'Break the work into tasks if useful','<p>Open the action and choose <strong>Add task</strong>. Enter the task title, owner, department, due date and priority; choose <strong>Save task</strong>.</p><p>For “Refresh loading bay markings”, a task might be “Agree pedestrian route with logistics team”.</p>','The task belongs to its parent action and is also visible in the Tasks register.') +
    step(3,'Complete each task','<p>Open a task, record any evidence references and enter a completion comment explaining what actually happened. Choose <strong>Complete task</strong>.</p>','The task shows completed. The parent action’s completed-task count increases.') +
    step(4,'Complete the action and plan the check','<p>After all of its tasks are finished, enter the action’s <strong>Completion comment</strong>, <strong>Effectiveness reviewer</strong> and <strong>Effectiveness review date</strong>. Choose <strong>Complete action</strong>.</p><p>For a same-day demo, choose today as the review date. For a real workflow, allow enough time to observe whether the change works.</p>','The action becomes <strong>Awaiting effectiveness</strong>. It is not yet verified as Effective.') +
    '''<div class="note"><strong>Audit-created actions:</strong> a corrective action raised by an audit can exist without a separate incident. It keeps its audit source link. Preventive actions can also exist independently, for example following a trend review.</div>'''),
('closure', 'Check effectiveness and close', '''<p><strong>Suggested people:</strong> Liam checks the outcome; an authorised incident manager closes the incident. Separate the reviewer from the action owner in your proposed operating model, while demonstrating both as Alex.</p>''' +
    step(1,'Make the effectiveness decision','<p>Open an action marked <strong>Awaiting effectiveness</strong>. On or after the planned review date, choose <strong>Effective</strong> or <strong>Ineffective</strong>, enter a <strong>Review evidence / comment</strong> and click <strong>Record effectiveness</strong>.</p><p>Use observable evidence: “Three shift checks found no blocked pedestrian routes.” A completion comment such as “done” is not an effectiveness check.</p>','The action retains the reviewer, review date and outcome comment.') +
    step(2,'Follow up if the action did not work','<p>If it is <strong>Ineffective</strong>, choose <strong>Create follow-up action</strong>. Describe the revised approach, assign it and complete its work and effectiveness review.</p>','The original result stays in history. The follow-up preserves the source incident associations and any audit provenance.') +
    step(3,'Check the closure conditions','<p>Return to the incident. Its required investigation must be complete. If action is required, it must have a linked action. All linked work must meet the effectiveness conditions, including effective follow-ups for ineffective actions.</p>','The closure panel either allows closure or explains the remaining blockers.') +
    step(4,'Record the decision to close','<p>Enter a meaningful <strong>Closure note</strong> and choose <strong>Close incident</strong>. Read the <strong>History</strong> tab to check the sequence of decisions.</p>','The incident is <strong>Closed</strong>. <strong>Reopen incident</strong> can return it to the active workflow if new information requires further work.') +
    '''<div class="note warm"><strong>Shared action reminder:</strong> ACT-093 is linked to INC-261 and INC-245. Review its associated incidents before making changes, because the outcome contributes to closure checks on each.</div>'''),
('trends', 'Turn patterns into prevention', '''<p><strong>Suggested people:</strong> Ethan spots the pattern; Sam or an EHS manager creates preventive work.</p>''' +
    step(1,'Preview a meaningful group','<p>Open <strong>Incident → Trends & prevention</strong>. Set the event date range and any type, subtype, department or cause criteria. Preview the trend and read the matching incidents before deciding on an action.</p><p>For the samples, include September 2026 and Near Miss events at Cork.</p>','You see which events match, rather than relying on a total without the underlying records.') +
    step(2,'Create prevention from the matches','<p>Create a preventive action, explaining the common issue and desired improvement. Set its owner and due date, then save.</p>','The action stores the criteria and a snapshot of matched incident IDs. Initial associations include matching open incidents.') +
    step(3,'Keep the evidence understandable','<p>On the saved action use <strong>Refresh trend snapshot</strong> if you want to capture the latest matches. Review the associated incidents separately.</p>','The saved trend results update. Refreshing the snapshot does not automatically rewrite the action’s incident associations.') +
    '<p>The preventive work then follows the same task completion and effectiveness checks as any other action.</p>'),
('reports', 'Use reports and exports', '''<p><strong>Suggested person:</strong> Ethan or Alex. Open <strong>Incident → Reports</strong>, select the report and apply its filters before exporting.</p>''' + table(['Report','What it helps you understand'],[
    ['Incidents by type / subtype','Which event categories are occurring most often.'],
    ['Incidents by cause','Which recorded causes need attention. A record may have multiple causes.'],
    ['Calendar days lost by department','Inclusive lost-time days allocated to departments. Restricted duties are excluded from lost-time totals.'],
    ['Action / task tracking','Who owns follow-up, its status and due dates.'],
    ['Incident tracking','The incident lifecycle, investigation and closure position.'],
]) + '''<div class="note"><strong>Choose the correct date meaning.</strong> Incident reports filter the event date. Action / task tracking filters due dates. A change of report can therefore change which records are included.</div>
<ol><li>Choose the report and date range; narrow the site, department or other available filters.</li><li>Read the displayed rows and counts.</li><li>Use <strong>Export CSV</strong> for spreadsheet work. Alex can configure columns in <strong>Settings → Export layout</strong>.</li><li>Use <strong>Print / save PDF</strong> and choose “Save as PDF” in the browser’s print dialog.</li></ol><p>Exported custom fields come from the saved report template data. A missing field on an older record may legitimately be blank.</p>'''),
('help', 'Questions and practice checklist', '''<details><summary>Why can’t I submit an incident?</summary><p>Check the required report fields, the type / subtype, assigned investigator rules and required custom questions. Use Save draft while information is incomplete.</p></details>
<details><summary>Why is Complete action disabled?</summary><p>Finish every task linked to that action first. Then provide a completion comment, effectiveness reviewer and review date.</p></details>
<details><summary>Why can’t I record effectiveness yet?</summary><p>The planned review date may be in the future. The check becomes available on that date. Use today’s date when deliberately practising the whole workflow in one session.</p></details>
<details><summary>Why can’t I close the incident?</summary><p>Read the closure blockers. Common reasons are an unfinished required investigation, no action when action is required, unfinished linked work, or an ineffective action whose follow-up is not yet effective. Enter a closure note too.</p></details>
<details><summary>Where has my template gone?</summary><p>Check that it is Published, its module is Incident, and its purpose matches Report or Investigation. Check the incident type’s template settings and any site visibility rules.</p></details>
<details><summary>Will the system send an email or store my uploaded evidence?</summary><p>This prototype demonstrates the fields and workflow. It does not send emails or external reports, run real background notifications, or upload evidence files to a server. Evidence names and reference links are retained only in the demo record.</p></details>
<details><summary>What do reportee, root cause and effectiveness mean?</summary><p><strong>Reportee:</strong> a person or destination that should receive information. <strong>Root cause:</strong> the underlying reason the event occurred. <strong>Effectiveness:</strong> evidence that the completed action achieved its intended result. <strong>Closure:</strong> the final recorded decision after the required checks.</p></details>''' + checklist([
    'I can find INC-252 and explain its linked action.',
    'I recorded an effectiveness decision and closed the practice incident.',
    'I can explain incident → investigation → action → task.',
    'I know Report and Investigation forms come from Form Builder.',
    'I understand why completing an action is followed by an effectiveness check.',
    'I can find overdue work or choose a report for my site.',
    'I understand the fictitious role examples and the admin-only demo.',
])),
]

AUDIT_PROFILES = {
    'admin': {'label': 'Alex · Workspace administrator', 'text': 'Alex sets up the audit structure and templates, oversees programmes and demonstrates every role with the admin login.', 'links': [['quick-demo','Practice run'], ['templates','Templates'], ['planning','Plans and programmes']]},
    'lead': {'label': 'Sam · Lead auditor', 'text': 'Sam prepares the audit, records objective evidence, confirms findings and explains the follow-up links within his assigned site.', 'links': [['schedule','Schedule'], ['findings','Record findings and scores'], ['trail','Audit trail']]},
    'auditee': {'label': 'Jordan / Jamie · Auditee', 'text': 'The auditee provides evidence and explains the work being audited. Being named as an auditee should not automatically grant editing or approval rights.', 'links': [['big-picture','Understand the process'], ['schedule','Participants'], ['findings','Evidence and findings']]},
    'reviewer': {'label': 'Liam · Express reviewer', 'text': 'Liam reviews an Express audit and confirms its classifications and comments. The confirmation routes any required follow-up.', 'links': [['express','Express review'], ['findings','Finding outcomes']]},
    'owner': {'label': 'Priya · Programme / action owner', 'text': 'Priya monitors the programme and completes assigned follow-up through the Incident module. Completing an audit does not complete its corrective work.', 'links': [['planning','Programme oversight'], ['findings','Follow-up links'], ['reports','Reports']]},
    'designer': {'label': 'Sofia · Form designer', 'text': 'Sofia designs reusable audit questions and scoring. Alex publishes the approved form for use in scheduling.', 'links': [['templates','Build a form'], ['findings','Scoring']]},
    'reader': {'label': 'Ethan · Site manager / reader', 'text': 'Ethan monitors audit coverage, open trail items and programme scores for his site.', 'links': [['screens','Page map'], ['trail','Evidence to revisit'], ['reports','Reports']]},
}

AUDIT = [
('start','Start here','''<div class="grid two"><div class="card"><h3>Open the prototype beside this guide</h3><ol><li>Enter invitation code <code>482916</code>.</li><li>Sign in as <code>admin@northstar.example</code>, password <code>Demo123!</code>.</li><li>Expand <strong>Audit</strong> in the workspace menu.</li><li>Open <strong>Audits</strong> to find the practice record.</li></ol><p>If already signed in, start at step 3.</p></div><div class="card"><h3>Start with a real example in the demo</h3><p>You will complete a scored workplace audit, classify findings and follow the links to corrective work.</p><p><a href="#quick-demo">Start the 15-minute practice run →</a></p><p><a href="#people">Meet the example audit team →</a></p></div></div>
<div class="note warm"><strong>Demo behaviour:</strong> the app keeps changes while you navigate in the same tab. Reloading or signing out resets the sample data. All dates in the practice audit are based on the demo’s current date. There are no real emails or background schedule runs; recurring audits are generated manually in the prototype.</div>'''),
('big-picture','The big picture','''<p>An <strong>audit plan</strong> is the overall assurance plan for a period. A <strong>programme</strong> groups related audits. An <strong>audit</strong> is one scheduled inspection or review. A <strong>finding</strong> records what the auditor discovered against a question.</p>
<div class="journey" aria-label="Audit workflow"><span>1. Publish a form</span><b>→</b><span>2. Plan & programme</span><b>→</b><span>3. Schedule</span><b>→</b><span>4. Record & confirm</span><b>→</b><span>5. Follow up</span></div>
''' + table(['Method','How it works','Sample form'],[
    ['Standard','Record answers and classify findings. Confirm individual questions or complete the whole audit.','Management system assurance'],
    ['Scorable','A Standard audit with numeric scores on applicable questions.','5S & safety scored audit'],
    ['Express','A short walkabout or inspection. Save and send for review, or directly confirm when the operating process permits it.','Workplace safety walkabout'],
]) + '''<div class="note"><strong>Two different kinds of completion:</strong> confirming an audit finishes its inspection record. Linked incidents and actions can still be open and must be managed in the Incident module.</div>
<h3>Subject areas are not company structure</h3><p>Health & Safety, Environment and Quality describe what the plan covers. These are subject areas (sometimes called “domains” in older systems). They are separate from <strong>Business unit → Site → Location → Department</strong>, which describes where the work happens.</p>'''),
('people','Who does what?',people('Audit',AUDIT_PROFILES,[
    persona('AM','Alex Morgan','Workspace administrator','Maintains programme types, forms and external auditees; oversees the presentation.','All Northstar sites'),
    persona('SO','Sam O’Brien','Lead auditor','Prepares the audit, gathers evidence, classifies and confirms findings.','Dublin · assigned audits'),
    persona('JK','Jordan Kelly','Employee auditee','Explains the work and provides evidence. Can own follow-up if separately assigned the required role.','Cork · Logistics'),
    persona('JW','Jamie Walsh','Third-party auditee','Represents Greenline Engineering during supplier assurance. Being listed here is not a login or access grant.','Named supplier audit'),
    persona('LC','Liam Connor','Express reviewer','Checks a submitted walkabout before confirming its findings and follow-up.','Dublin · assigned reviews'),
    persona('PS','Priya Shah','Programme / action owner','Coordinates the programme and follows corrective work through to an effectiveness check.','Assigned programme and work'),
    persona('SR','Sofia Reed','Form designer','Builds questions, sections and scoring in draft forms. Alex publishes them.','Audit templates'),
    persona('EB','Ethan Byrne','Site manager / reader','Reads coverage, scores and outstanding audit trail evidence for his site.','Cork · read access'),
],[
    ['Lead auditor','Assigned audit answers, evidence and schedule details','Confirm questions / complete audit','Read scoped templates and history'],
    ['Secondary auditor','Contribute if given the relevant scoped permissions','Confirmation only if separately authorised','Assignment alone is not a permission'],
    ['Auditee','Provide evidence to the auditor','No approval by default','May be employee or third party'],
    ['Express reviewer','Review classifications and comments','Confirm submitted Express findings','Assigned reviews within scope'],
    ['Programme owner','Coordinate programme and schedules','Complete programme when eligible','Monitor audit and follow-up progress'],
    ['Action owner','Assigned corrective / preventive work in Incident','Complete work, then submit for effectiveness','No automatic audit edit access'],
    ['Form designer','Draft questions, sections and scoring','Publish reserved for Alex in this example','Form Builder access'],
    ['Site reader','Read permitted audits only','None','Scoped coverage and score reports'],
    ['Workspace administrator','All demo steps','All demo confirmation steps','Programme types, auditees, forms and roles'],
],'Sam could have <strong>Lead auditor at Dublin</strong> and <strong>Incident investigator at Cork</strong>. Priya could own a programme without having permission to publish forms. Permissions should combine the role’s allowed function with its assigned scope.')),
('quick-demo','Your first practice run','''<p>Use the existing scored audit so you can learn the workflow before creating a plan. This example deliberately produces one incident, one corrective action and one preventive action.</p><div class="practice-summary"><span>About 15 minutes</span><span>AUD-104 · Dublin · 5S & safety review</span><span>4 questions · 3 follow-ups</span></div>''' +
    step(1,'Open the scored audit','<p>Go to <strong>Audit → Audits</strong>, search <code>AUD-104</code> and open <strong>Dublin · 5S & safety review</strong>. Use the <strong>Questions</strong> tab and set <strong>Question view</strong> to show all questions.</p>','The audit has four questions using the published 5S & safety scored audit form.') +
    step(2,'Confirm the first finding','<p>For <strong>Are walkways clear and correctly marked?</strong>, answer <strong>No</strong>, choose <strong>Major Non-Conformance</strong>, score <strong>1</strong> and comment “Pedestrian segregation missing at the loading bay approach.” Tick <strong>Confirm and lock question 1</strong>, then choose <strong>Save findings</strong>.</p><p class="small">Normal role: lead auditor. The sample employee auditee is Sam, so the form’s major-finding assignment rule routes the incident to him.</p>','Question 1 is locked and an Incident link appears. Progress is 25%; the saved score is provisionally 20% (1 out of 5).') +
    step(3,'Answer the remaining questions','<p>Use these practice answers. The score must be within the question’s configured range.</p>' + table(['Question','Answer / finding','Score','Comment'],[
    ['Equipment stored in designated locations?','No · Minor Non-Conformance','3','Equipment storage areas are not marked.'],
    ['Machine guards in place and inspected?','N/A finding','Leave blank','No machinery is included in this inspection scope.'],
    ['Emergency equipment accessible?','Yes · Opportunity for Improvement','4','Access is clear; improve extinguisher visibility.'],
]) + '<p>For N/A, choose the <strong>N/A finding type</strong>; an answer and score are not required, but its comment is.</p>','All four questions are ready for confirmation. The N/A question will be excluded from the score denominator.') +
    step(4,'Complete the audit record','<p>Enter a <strong>Closing note</strong>, for example “Inspection complete; route segregation, storage marking and equipment visibility follow-up assigned.” Choose <strong>Complete & confirm audit</strong>.</p>','The audit is <strong>Completed</strong>, questions are locked and progress is 100%. The overall score rounds to <strong>53%</strong>: (1 + 3 + 4) ÷ (5 + 5 + 5).') +
    step(5,'Follow the work into Incident','<p>Read the generated links: a major finding creates an incident, a minor finding a corrective action, and the improvement opportunity a preventive action. Open one link, inspect its source, then use <strong>Open source audit</strong> to return.</p>','The audit is completed while its follow-up work is still open. Continue those workflows using the <a href="incident-user-guide.html#actions">Incident guide</a>.') +
    '<div class="note warm"><strong>Practising again:</strong> confirmed questions cannot be edited in this prototype. Schedule another audit, or reload to restore the sample records when you are ready to discard all current demo changes.</div>'),
('screens','Find the right page',table(['Audit menu page','Use it to…','Good starting point'],[
    ['Overview','Monitor planned work, completion and follow-up','Open a due audit or a finding'],
    ['Audit plans','Create and inspect assurance plans','AP-001 · Northstar assurance plan'],
    ['Programmes','Group work by purpose and method','PG-002 · 5S & workplace safety'],
    ['Audits','Search, schedule and perform an audit','AUD-104 or AUD-105'],
    ['Findings & audit trail','Read findings and evidence needing another check','Audit trail from AUD-101'],
    ['Recurring schedules','Preview and generate repeated audits','RS-001 · Cork weekly walkabout'],
    ['Templates','Preview published Audit forms','5S & safety scored audit'],
    ['Reports','See coverage, scores, Express answers and action reports','Department coverage'],
    ['Settings','Maintain programme types and external auditees','Third-party auditees'],
]) + '<p>The audit detail has <strong>Questions, Details & evidence and History</strong> tabs. Use <strong>More filters</strong> in the register to narrow by plan, programme, site, department, auditor, auditee, method, status or date. The small information icon explains the current page.</p>'),
('templates','Build and reuse audit templates','''<p><strong>Suggested people:</strong> Sofia designs; Alex publishes. <strong>Audit → Templates</strong> previews the available published forms; <strong>Configuration → Form Builder</strong> is where they are created.</p>''' +
    step(1,'Choose the method first','<p>In <strong>Form Builder → Create form</strong>, enter a name, choose <strong>Audit</strong>, then choose <strong>Standard, Scorable or Express</strong>. Review the standard title, site, scheduled date, lead auditor and scope fields.</p>','The method determines how its questions will be answered and, for Scorable, scored.') +
    step(2,'Design questions people can answer','<p>Add section headings to group questions. Drag or add components such as Yes / No, dropdown or long text. Enter labels, guidance, required settings and options. Use the Components search to reuse a field and then reorder it as needed.</p><p>Example: section “Emergency readiness”, Yes / No question “Are emergency exits clear?”, help text explaining what evidence to check.</p>','The right-hand preview reflects the form. Custom answer fields become the audit’s questions; section headings organise them.') +
    step(3,'Set scoring and visibility where relevant','<p>For a scored form, configure each question’s minimum, maximum and increment, such as 0 to 5 in steps of 1. Review question / template site visibility, default finding suggestions and the major-finding assignee option.</p>','Only questions visible for the scheduled site are included. A suggested finding is not a completed answer.') +
    step(4,'Publish for scheduling','<p>Review the form and publish it. Open <strong>Audit → Templates</strong> to preview the published version, then use it as a programme default or choose it when scheduling an audit.</p>','Draft forms do not appear as usable scheduling templates. An audit keeps a snapshot of its chosen published version.') +
    '<div class="note"><strong>Extend one audit without changing every future audit.</strong> Use <strong>Add question to this audit</strong> before completion. To reuse the entire question set, choose <strong>Copy to builder draft</strong>, review the new draft in Form Builder and publish it for future scheduling.</div><p>The mobile option describes intended availability for assigned users; this prototype uses the responsive web app and does not connect a separate mobile app.</p>'),
('planning','Set up plans and programmes','''<p><strong>Suggested people:</strong> Alex creates the plan; Priya or another programme owner coordinates its audits.</p>''' +
    step(1,'Create the assurance plan','<p>Open <strong>Audit → Audit plans → Create plan</strong>. Enter the plan name, start and end years, relevant business areas and the remaining descriptive information. Save.</p><p>Example: “Northstar annual assurance plan”, covering the current year, Health & Safety, Environment and Quality.</p>','The plan is the parent container for its programmes.') +
    step(2,'Create a programme inside it','<p>Open the plan and choose <strong>Create programme</strong>. Enter its name, programme type, owner, review date and description. Choose a compatible published default form.</p><p>Example: “5S & workplace safety”, Standard programme type with a Scorable audit form.</p>','The programme appears in the plan and can now hold scheduled audits and recurring rules.') +
    step(3,'Monitor and maintain the programme','<p>Open the programme to schedule audits, add a recurring schedule or inspect its audit list. Keep the owner and review date up to date.</p>','The programme shows the work it groups. Completion is available only when its audit and recurrence conditions are satisfied.') +
    '''<div class="note warm"><strong>Date and archive rules:</strong> the plan’s start year locks after a programme exists. Its end year cannot exclude existing audits or review dates. Completed audits / programmes and records linked to incidents or actions cannot be archived. To archive eligible parents, first archive eligible children and pause their schedules. Archive preserves data; it is not deletion.</div>'''),
('schedule','Schedule an audit','''<p><strong>Suggested person:</strong> Sam, a lead auditor with scheduling permission in the relevant scope. In the demo, use Alex.</p>''' +
    step(1,'Choose the programme and template','<p>On <strong>Audit → Audits</strong> choose <strong>Schedule audit</strong>, or schedule directly from a programme. Enter the name, choose an active programme, the department / site and a published compatible Audit form.</p>','The selected form must contain questions visible for that site. Programme options include their plan year to distinguish annual versions.') +
    step(2,'Assign people and time','<p>Choose the lead auditor, Employee or Third-party auditee and the auditee. Set the start date / time and duration with its unit. Add secondary auditors, people observed or other participants when useful.</p><p>For a supplier audit, select Jamie Walsh at Greenline Engineering. Alex maintains this record in <strong>Settings → Third-party auditees</strong>.</p>','The audit records who is auditing, who is being audited and when the work is planned. An external auditee is a contact, not an automatically created app user.') +
    step(3,'Explain the scope and save','<p>Describe the scope / objectives and any additional information. The initial audit date must fall within the plan period. Save the audit.</p>','A new audit appears in the register with unanswered questions from the template snapshot.') +
    step(4,'Prepare for fieldwork','<p>Open the audit and use <strong>Hard copy</strong> for a blank fieldwork report. Use <strong>Details & evidence</strong> for notes and evidence names or reference links; click <strong>Save notes & evidence</strong>.</p>','The hard-copy preview can be downloaded as HTML or printed / saved as PDF. Notes and references stay with the record; this demo does not upload file contents.') +
    '<p><strong>Edit schedule details</strong> can adjust permitted information before completion. The programme, department / site and template are fixed on an existing audit to preserve its recorded answers.</p>'),
('findings','Record, score and confirm findings','''<p><strong>Suggested person:</strong> Sam, the lead auditor. Work through the <strong>Questions</strong> tab, one question at a time or with the all-questions view.</p>
<ol><li>Read the question’s guidance and gather evidence.</li><li>Enter the answer, select its finding type and record the finding comment.</li><li>For Scorable questions, enter a valid score within its minimum / maximum / increment.</li><li>Use <strong>Save findings</strong> to preserve work. For a Standard / Scorable question ready to finish, tick <strong>Confirm and lock question</strong> before saving.</li><li>When every question is ready, enter the closing note and choose <strong>Complete & confirm audit</strong>.</li></ol>
<div class="note"><strong>Confirmation routes follow-up.</strong> Saving an unconfirmed finding preserves progress. Confirming and locking a question creates the relevant linked incident or action once. Completing the audit confirms all remaining questions.</div>
<h3>What each finding creates</h3>''' + table(['Finding type','Follow-up outcome'],[
    ['Major Non-Conformance','Creates an Audit Non-Conformance incident in the Incident module. It may be Draft if required custom incident answers still need completing.'],
    ['Minor Non-Conformance','Creates a corrective action in Incident → Actions.'],
    ['Opportunity for Improvement','Creates a preventive action in Incident → Actions.'],
    ['Insufficient Finding','Creates an audit trail item to revisit in a later audit.'],
    ['Conforming / Observation / Good Practice','Records the finding without automatic incident or action creation.'],
    ['N/A','Excludes the question from scoring. Requires a comment explaining why it is not applicable.'],
]) + '''<p>Non-conformances, improvement opportunities and insufficient findings require a comment. Use objective evidence, not just “failed”. A confirmed question is locked; this prototype does not provide an audit reopening workflow.</p>
<h3>Understand the score</h3><p class="path">Overall score = total saved applicable scores ÷ total applicable maximum scores × 100</p><p>With scores 1, 3 and 4 out of 5, plus one N/A question: <strong>8 ÷ 15 = 53%</strong> when rounded. N/A contributes neither score nor maximum. Before all applicable questions are scored, the displayed score is provisional; it reflects only saved scored answers, not a final result.</p>
<h3>Follow the source, not duplicate records</h3><p>Use the generated Incident / Action links. Assignment of a major incident follows the form’s rule: it can use the employee auditee, otherwise the lead auditor; third-party auditees fall back to the lead. If the generated incident is Draft, complete its required report answers and submit it in Incident.</p><p>Use <strong>Open source audit</strong> to return. Manage tasks, completion and effectiveness checks in the <a href="incident-user-guide.html#actions">Incident guide</a>. The audit can be completed while those records remain open.</p>'''),
('express','Perform and review an Express audit','''<p><strong>Suggested people:</strong> Sam records the walkabout; Liam reviews it. Demonstrate both parts as Alex.</p>''' +
    step(1,'Open the sample walkabout','<p>Open <strong>AUD-105 · Cork · weekly walkabout</strong>. Answer its four questions, including the observation text. Select the appropriate finding types and comments.</p>','The form is the published <strong>Workplace safety walkabout</strong> Express template.') +
    step(2,'Send it for review','<p>Enter the <strong>Closing note</strong>, choose a reviewer and click <strong>Save & send for review</strong>. All required questions must be ready.</p>','The audit becomes <strong>Awaiting review</strong>. Answers are read-only, but the reviewer can check and adjust the finding classifications and comments.') +
    step(3,'Confirm the review','<p>As the reviewer, check the evidence, classifications and comments, enter the required review comments and click <strong>Confirm review & findings</strong>.</p>','The audit becomes <strong>Reviewed</strong>, findings lock and any incident / action follow-up is generated.') +
    '''<div class="note"><strong>100% answered is not formally completed.</strong> An Express audit can have all answers saved and still await submission or confirmation. Where the operating process permits it, <strong>Complete & confirm audit</strong> offers direct confirmation instead of the separate review route.</div>'''),
('trail','Carry unresolved evidence forward','''<p>An <strong>Insufficient Finding</strong> means there was not enough evidence to reach a conclusion. The audit can finish, while its trail item remains for a later audit in the same programme lineage.</p>''' +
    step(1,'Find what needs another check','<p>Open <strong>Audit → Findings & audit trail → Audit trail</strong>. Filter Open items and inspect the source.</p><p>The sample <strong>AUD-101 · September management review</strong> asks to recheck contractor competency evidence.</p>','You can see the source audit, original question and the evidence that must be revisited.') +
    step(2,'Carry it into the next audit','<p>Open <strong>AUD-103 · Management controls · Dublin</strong>. In its extension area find <strong>Evidence to revisit</strong> and choose <strong>Carry into this audit</strong> for the competency item.</p>','A follow-up question is added, retaining the original comment and source audit reference. The same item is not added twice to this audit.') +
    step(3,'Resolve it with a conclusion','<p>Gather the missing evidence. Answer the carried question, write a clear comment, choose a conclusive finding such as Conforming and confirm / lock it, then save.</p><p>Example: “Current competency certificates inspected for all contractors in this audit scope.”</p>','The original trail item is marked resolved with a link to this audit. Insufficient Finding or N/A would leave it unresolved.') +
    '<p>Use Open / Resolved / All, programme, site and text filters to find trail items. An unresolved trail is an outstanding evidence check, not automatically an Incident task.</p>'),
('recurrence','Set up recurring audits','''<p><strong>Suggested person:</strong> Alex or a programme owner with schedule management permission. A recurring schedule is a rule that generates individual audits; pausing it does not erase audits already generated.</p>''' +
    step(1,'Create the schedule','<p>Open <strong>Audit → Recurring schedules → Create schedule</strong>, or use <strong>Copy as recurring schedule</strong> on an existing audit. Set the programme, template, people, department, duration and scope.</p><p>Choose Daily, Weekly, Monthly, Quarterly or Annually, enter the initial date / time and notification lead days, and optionally set an end date.</p>','The saved rule has a clear starting point and can be paused or resumed.') +
    step(2,'Preview before generating','<p>Open the rule and select a preview count of 3, 6 or 12. Review the dates, planned notification dates, plan / programme and any already existing audit markers.</p><p>Try <strong>RS-001 · Cork · weekly walkabout</strong>. The first occurrence already exists as AUD-105.</p>','The preview shows the first requested number of occurrences from the rule’s initial anchor, including any that already exist.') +
    step(3,'Generate the missing audits','<p>Click <strong>Generate previewed audits</strong>. For the sample weekly rule, a six-occurrence preview creates five new audits because the first already exists. Repeating generation of those same occurrences does not duplicate them.</p>','The generated audits appear in the register. Annual plan / programme rollover is created or reused when occurrences extend beyond the original plan period.') +
    '<div class="note warm"><strong>This prototype needs the Generate button.</strong> Lead days demonstrate when notifications would be due; no email or cron service runs here. Monthly dates keep their original anchor: a 31st falls on the last day of a shorter month, then returns to the 31st when possible.</div><p>Use <strong>Pause schedule</strong> to prevent generation. Review and edit the rule before resuming. Dates are illustrative tenant-local date / time values in this demo.</p>'),
('reports','Read reports and maintain settings','''<p><strong>Suggested people:</strong> Ethan monitors his site; Alex maintains the shared configuration.</p>
<h3>Audit reports</h3><p>Open <strong>Audit → Reports</strong>, choose the tab and filter by programme, site and date range.</p>''' + table(['Report tab','How to read it'],[
    ['Department coverage','Shows the distribution of active audits by department, including planned audits. It is not a count of completed audits only.'],
    ['Programme scores','Averages audit percentages with saved scores. Incomplete audit scores are provisional; all-N/A audits have no applicable score.'],
    ['Express by question','Groups saved Express answers by question and answer value. Useful for recurring walkabout patterns.'],
    ['Action reports','Lists completed / reviewed audits with their findings and follow-up links. Open an audit or print its action report.'],
]) + '''<p>Use <strong>Export CSV</strong> after filtering. On an audit, <strong>Hard copy</strong> produces a blank fieldwork report; <strong>Action report</strong> produces the completed results. In the report preview use <strong>Download HTML</strong> or <strong>Print / save PDF</strong>. Close it with <strong>Close preview</strong>.</p>
<h3>Settings</h3>''' + table(['Settings tab','What it controls'],[
    ['Programme types','Names, descriptions and Standard / Express method. A type’s method is locked while it is in use, to protect existing programmes.'],
    ['Third-party auditees','Contact name, company, email / phone and active status. Name and company are required. Inactive contacts remain on old records but cannot be newly selected.'],
]) + '<p>Template questions and scoring belong in <strong>Configuration → Form Builder</strong>. Role assignments belong in <strong>Configuration → Roles & permissions</strong>. Notification / cron configuration is a separate administration concept; Audit recurring generation is manual in this presentation.</p>'),
('help','Questions and practice checklist','''<details><summary>Why can’t I find my template when scheduling?</summary><p>Check that the form is Published, belongs to Audit, is compatible with the programme method and has questions visible for the selected site. A Draft form cannot be used.</p></details>
<details><summary>Why can’t I finish the audit?</summary><p>Check required answers, finding comments and valid numeric scores. N/A needs a reason but does not need an answer or score. Enter the closing note. An Express submission also needs a reviewer; review confirmation needs review comments.</p></details>
<details><summary>Why can’t I change a question I have confirmed?</summary><p>Confirmation locks the question and routes follow-up. Completed audits are also locked. This prototype has no audit reopening workflow. For practice, create another audit or deliberately reload to reset demo data.</p></details>
<details><summary>Why is the audit completed while its incident is still open?</summary><p>Audit completion means the inspection and findings are recorded. Incident investigation, actions, tasks and effectiveness checks are separate follow-up work. Use the linked record and the Incident guide.</p></details>
<details><summary>Why did a major finding create a Draft incident?</summary><p>The Incident report template may contain required custom questions that cannot be answered from the audit alone. Complete those answers and submit the report in Incident. Do not create a second incident for the same finding.</p></details>
<details><summary>Why did recurring generation add fewer audits than the preview count?</summary><p>Already generated occurrences are not duplicated. The preview includes existing dates and starts at the schedule’s original initial date, rather than automatically moving forward from today.</p></details>
<details><summary>Why can’t I archive this record?</summary><p>Completed audits / programmes and records with linked incidents or actions are protected. Eligible parent records also require eligible children to be archived and their schedules paused first. Read the displayed blocker before proceeding.</p></details>
<details><summary>What do auditee, non-conformance and audit trail mean?</summary><p><strong>Auditee:</strong> the employee or third party whose work is being reviewed. <strong>Non-conformance:</strong> a finding that the requirement being checked has not been met. <strong>Audit trail here:</strong> an unresolved evidence question carried forward to a later audit. <strong>History:</strong> the record of changes and decisions on one audit.</p></details>''' + checklist([
    'I found AUD-104 and read its four questions.',
    'I confirmed a major finding and followed its Incident link.',
    'I completed the scored practice audit and understand its 53% result.',
    'I know that audit completion does not close corrective work.',
    'I can explain plan → programme → audit → finding.',
    'I know Audit templates come from Form Builder.',
    'I can send an Express audit for review or carry an audit trail question forward.',
    'I can preview a recurring schedule without expecting automatic emails.',
    'I understand the fictitious role examples and the admin-only demo.',
])),
]


def build(module, chapters, profiles, title, subtitle, duration):
    other_links = ''.join(f'<a href="{name}-user-guide.html">{name.title()} guide ↗</a>' for name in ['risk', 'incident', 'audit', 'law', 'inspection'] if name != module)
    search_hint = {'incident': 'effectiveness, causes, draft…', 'audit': 'score, recurring, auditee…', 'law': 'profile, evidence, updates…', 'inspection': 'QR, ladder, finding, template…'}[module]
    nav = ''.join(f'<a href="#{id}"><span>{n:02}</span>{html.escape(label)}</a>' for n, (id, label, _) in enumerate(chapters, 1))
    sections = ''.join(f'<section id="{id}" data-title="{html.escape(label, quote=True)}"><div class="section-head"><span class="section-no">{n:02}</span><div><h2>{label}</h2></div></div>{body}</section>' for n, (id, label, body) in enumerate(chapters, 1))
    profiles_js = {key: {k: v for k, v in value.items() if k != 'label'} for key, value in profiles.items()}
    script = re.sub(r'const profiles = \{.*?\n    \};', 'const profiles = ' + json.dumps(profiles_js, ensure_ascii=False) + ';', SCRIPT, count=1, flags=re.S)
    script = script.replace('oleoq-risk-guide-checklist-v1', f'oleoq-{module}-guide-checklist-v1')
    output = f'''<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="A practical OleoQ {module} user guide with fictional team responsibilities and step-by-step prototype exercises."><title>{module.title()} user guide · OleoQ</title><style>{STYLE}{EXTRA_STYLE}</style></head>
<body><a class="skip" href="#main">Skip to the guide</a><div class="layout">
<aside class="side"><div class="brand"><svg width="29" height="32" viewBox="0 0 29 32" fill="none" aria-hidden="true"><path d="M14.5 2 26 7v9c0 6-5 10-11.5 14C8 26 3 22 3 16V7L14.5 2Z" stroke="currentColor" stroke-width="2"/><path d="m8 15 4 4 9-9" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>OleoQ</div><div class="side-caption">{module.upper()} · USER GUIDE</div><nav aria-label="Guide contents">{nav}</nav><div class="side-footer">Northstar Manufacturing<br>Prototype edition · October 2026<br><br>All names, records and examples in this guide are fictitious.</div></aside>
<main class="main" id="main"><div class="topline"><span>OLEOQ LEARNING CENTRE</span><div class="top-actions"><a class="button" href="http://127.0.0.1:3001/" target="_blank" rel="noopener">Open prototype ↗</a><button class="button" id="print-guide" type="button">Print / save PDF</button></div></div>
<header class="hero"><div class="eyebrow">{module.upper()} · A PRACTICAL USER GUIDE</div><h1>{title}</h1><p>{subtitle}</p><div class="hero-meta"><span>{duration} guided practice</span><span>Fictitious Northstar team</span><span>Admin-only prototype</span></div><a class="button primary" href="#quick-demo">Start the practice run →</a></header>
<div class="guide-links" aria-label="Other module guides">{other_links}<a href="#people">Who does what? ↓</a></div>
<div class="search-area"><label class="small" for="guide-search">Find something in this guide</label><input id="guide-search" type="search" placeholder="Try: {search_hint}" autocomplete="off" aria-controls="search-results"><div class="search-results" id="search-results" hidden aria-label="Matching chapters"></div><p class="small" id="search-status" aria-live="polite"></p></div>
{sections}<footer class="footer">OleoQ · {module.title()} user guide · October 2026<br>Based on the current Northstar prototype and its local module reference. This is an operating walkthrough, not a claim that proposed roles are enforced. <a href="#start">Back to the beginning ↑</a></footer></main></div><script>{script}</script></body></html>'''
    destination = ROOT / 'public' / f'{module}-user-guide.html'
    destination.write_text(output, encoding='utf-8')
    print(f'Created {destination.name}: {len(chapters)} chapters, {len(output):,} characters')


if __name__ == '__main__':
    build('incident', INCIDENT, INCIDENT_PROFILES, 'From report<br><em>to resolution.</em>', 'Learn how to record an event, understand its causes, organise the work and check that the problem is solved. Follow one clear example, then explore the rest at your own pace.', '10-minute')
    build('audit', AUDIT, AUDIT_PROFILES, 'From inspection<br><em>to improvement.</em>', 'Learn how plans, programmes and forms become practical audits. Record clear findings, understand the score and follow every issue through to the right next step.', '15-minute')

    import runpy
    runpy.run_path(str(ROOT / 'scripts' / 'build-law-user-guide.py'), run_name='__main__')
    runpy.run_path(str(ROOT / 'scripts' / 'build-fieldwork-user-guides.py'), run_name='__main__')
