"""Update Risk QR guidance and build the standalone Inspection guide.

Run: python scripts/build-fieldwork-user-guides.py
Uses the established Risk HTML theme; no external assets are required.
"""
from pathlib import Path
import re
import runpy
import html

ROOT = Path(__file__).resolve().parents[1]

RISK_QR = '''<section id="qr-fieldwork" data-title="QR equipment ladder labels scan camera phone periodic review due reminders responsible person scheduled jobs">
<div class="section-head"><span class="section-no">12</span><div><h2>QR labels, field reviews and due reminders</h2><p>For the assessment owner, administrator and people working around the site.</p></div></div>
<p>A QR label identifies a particular Risk assessment. Attach it to the relevant equipment, such as <strong>Ladder LAD-001</strong>. Scanning opens that assessment after sign-in; an approved assessment opens its periodic review form. The QR does not approve the assessment or complete a review.</p>
<div class="grid"><div class="card"><h3>Alex prepares the label</h3><ol><li>Open <strong>Risk → Risk assessments</strong> and find <code>RA-LAD001</code>.</li><li>Open the record and click <kbd>QR label</kbd>.</li><li>Check the equipment name, responsible person and current review date.</li><li>Use <kbd>Print</kbd> or <kbd>Download label</kbd> to produce a label. Keep its white border clear and the code readable.</li><li>Use <kbd>Test QR link</kbd> to try the route on this computer.</li></ol></div><div class="card"><h3>Priya reviews at the equipment</h3><ol><li>Open <kbd>Scan QR label</kbd> from Workspace or the top-bar scan icon.</li><li>Tap <kbd>Start camera</kbd> and allow camera access when prompted. Point at the printed code.</li><li>Alternatively choose a QR image, or enter <code>RA-LAD001</code> and click <kbd>Open record</kbd>.</li><li>Read the approved assessment and check whether its controls are still valid.</li><li>If unchanged, enter review comments and a future next review date, then <kbd>Save review</kbd>. If changed, use <kbd>Edit / rescore</kbd> and follow the approval workflow.</li></ol></div></div>
<div class="note"><strong>Two different records can describe one ladder.</strong> <code>RA-LAD001</code> describes risks and controls; <code>INS-LAD001</code> is a routine condition questionnaire. They have separate QR labels. Use the <a href="inspection-user-guide.html#quick-demo">Inspection ladder walkthrough</a> for the checks and next inspection date.</div>
<h3>Try it in five minutes</h3><ol><li>Open the bell icon <kbd>Due-date reminders</kbd> and choose <strong>Priya Shah</strong> under Responsible person.</li><li>Find the ladder Risk review due today. Open it from the reminder, or type <code>RA-LAD001</code> in the scanner.</li><li>Enter a review comment such as “Controls checked against the current task; no changes required.” Choose a future review date and save.</li><li>Reopen the bell. The old due-today reminder disappears when the new date is outside the configured upcoming window.</li><li>Open <kbd>History &amp; reviews</kbd> to read the review entry.</li></ol><p class="small">This fictional exercise demonstrates the software workflow. Review actual equipment using your organisation’s procedure and manufacturer instructions.</p>
<h3>How due reminders work</h3><p>The bell is a <strong>live in-app preview</strong> of enabled reminder rules. Risk reminders use the approved assessment’s <strong>owner and review date</strong>; Inspection reminders use the assigned inspector and scheduled date. Filter by responsible person to demonstrate the hand-off.</p><p>Use <kbd>Manage reminder schedules</kbd> or <strong>Configuration → Scheduled jobs</strong>. The default <strong>Daily equipment &amp; risk reminders</strong> rule covers upcoming Risk reviews and Inspections within seven days. Overdue rules cover late items. Rules must be enabled, include the record type and matching company/site scope, and have owner reminders with in-app delivery selected to appear in the bell. Test previews use live Risk and Inspection dates; other module entries remain illustrative.</p>
<div class="note warm"><strong>Phone and prototype limits.</strong> Set the label’s website address to the deployed HTTPS workspace before printing for a phone. A localhost link works only on this computer. A direct link requires sign-in; scanning does not grant access. Camera and QR-image decoding happen on the device. If the camera is unavailable, use an image or reference. Demo edits reset on reload/sign-out and are not shared between devices. Background cron execution and automatic email delivery still require the backend; this demo sends no messages.</div>
<h3>Keep the label useful</h3><ul><li>Periodic reviews and revisions keep the assessment’s ID, so its existing QR still opens it.</li><li>Cloning creates a different assessment and needs a new label.</li><li>If the record is archived, scanning still identifies it but does not make it editable. Restore and follow reapproval as needed.</li><li>A missing record or a label from another workspace shows an error. Open the correct workspace or check the reference.</li></ul>
</section>'''

def update_risk():
    path = ROOT / 'public/risk-user-guide.html'
    text = path.read_text(encoding='utf-8')
    text = re.sub(r'\s*<section id="qr-fieldwork".*?</section>', '', text, flags=re.S)
    text = text.replace('    <section id="reports"', '    ' + RISK_QR + '\n\n    <section id="reports"', 1)
    text = text.replace('No. Configuration → Scheduled jobs demonstrates reminder configuration and test previews using its own sample records. It does not send notifications or evaluate the live Risk records you create.', 'No emails are sent. The bell previews live due reminders for Risk reviews and Inspections using enabled Scheduled jobs rules. Saving a new review date updates that preview. Background execution and email delivery require the backend. <a href="#qr-fieldwork">See QR labels and reminders</a>.')
    if 'id="fieldwork-guide-link"' not in text:
        text = text.replace('<div class="search-area">', '<div class="card" id="fieldwork-guide-link"><strong>New: equipment QR labels and mobile reviews.</strong> <a href="#qr-fieldwork">Learn the Risk QR workflow →</a> · <a href="inspection-user-guide.html">Open the Inspection guide →</a></div>\n    <div class="search-area">', 1)
    # Keep the established chapter style and regenerate numbering after insertion.
    count = 0
    def number(match):
        nonlocal count
        count += 1
        return match.group(1) + f'{count:02}' + match.group(2)
    text = re.sub(r'(<span class="section-no">)\d+(</span>)', number, text)
    chapters = re.findall(r'<section id="([^"]+)".*?<h2>(.*?)</h2>', text, re.S)
    nav = ''.join(f'<a href="#{id}"><span>{n:02}</span>{html.escape(re.sub("<[^>]+>", "", title))}</a>' for n,(id,title) in enumerate(chapters,1))
    text = re.sub(r'(<nav aria-label="Guide contents">).*?(</nav>)', lambda m:m.group(1)+nav+m.group(2), text, count=1, flags=re.S)
    text = text.replace("['reviews','See the result in history']", "['reviews','See the result in history'],['qr-fieldwork','Equipment QR reviews']")
    path.write_text(text, encoding='utf-8')
    print(f'Updated Risk guide: {len(chapters)} chapters')

def build_inspection():
    helpers = runpy.run_path(str(ROOT / 'scripts/build-user-guides.py'))
    step, table, persona, people, checklist, build = [helpers[n] for n in ['step','table','persona','people','checklist','build']]
    profiles = {
        'admin': {'label':'Alex · Administrator','text':'Alex configures the organisation and access, publishes forms, sets reminder rules and oversees the demo. Use his login to play every role.','links':[['quick-demo','Ladder practice'],['templates','Forms'],['reminders','Reminder rules']]},
        'coordinator': {'label':'Sam · Inspection coordinator','text':'Sam schedules Cork checks, chooses the department and inspector, and monitors overdue work and findings.','links':[['schedule','Schedule a check'],['findings','Track follow-up'],['reports','Reports']]},
        'inspector': {'label':'Priya · Inspector','text':'Priya scans the Dublin ladder label, records conditions and responses, completes fieldwork and schedules its next check.','links':[['quick-demo','Ladder practice'],['conduct','Record observations'],['qr','QR labels']]},
        'owner': {'label':'Jordan · Action owner','text':'Jordan carries out assigned corrective work in Incident and records completion evidence. An effectiveness reviewer checks the outcome.','links':[['responses','Respond to a finding'],['findings','Effectiveness and closure']]},
        'reviewer': {'label':'Liam · Effectiveness reviewer','text':'Liam verifies that assigned corrective work solved the problem in Incident. Inspection has no separate approval stage.','links':[['findings','Verify follow-up'],['reports','Review reports']]},
        'designer': {'label':'Sofia · Form designer','text':'Sofia creates draft Inspection questionnaires and reuses fields. Alex publishes the approved design in this suggested arrangement.','links':[['templates','Form Builder']]},
        'reader': {'label':'Ethan · Site reader','text':'Ethan reads Cork inspection records and findings to understand progress. His proposed read role does not let him change checks or schedules.','links':[['screens','Page map'],['reports','Read reports']]},
    }
    team = people('Inspection',profiles,[
        persona('AM','Alex Morgan','Workspace administrator','Creates structure and roles, publishes forms and configures reminder jobs.','All Northstar sites'),
        persona('SO','Sam O’Brien','Inspection coordinator','Schedules checks and coordinates overdue work and findings.','Cork · Logistics'),
        persona('PS','Priya Shah','Inspector / assessment owner','Checks Ladder LAD-001 and separately reviews its Risk assessment.','Dublin · Maintenance'),
        persona('JK','Jordan Kelly','Corrective action owner','Carries out assigned corrective work and provides evidence in Incident.','Cork · assigned actions'),
        persona('LC','Liam Connor','Effectiveness reviewer','Checks whether assigned action work solved the issue. A learning persona, not a current working login.','Assigned Incident reviews'),
        persona('SR','Sofia Reed','Form designer','Builds draft questionnaires and reusable components. A learning persona.','Inspection forms'),
        persona('EB','Ethan Byrne','Site reader','Reads records, findings and reports. A learning persona.','Cork · read access'),
    ],[
        ['Administrator','Structure, roles, forms and schedules','All presentation steps','Publish forms; configure reminder rules'],
        ['Coordinator','Schedules within site scope; assign inspector','Coordinate next checks','Read site reports and overdue work'],
        ['Inspector','Assigned answers, observations and responses','Complete fieldwork after required checks','Read assigned records; print/scan their labels'],
        ['Action owner','Assigned Incident action work and evidence','Complete work; reviewer checks effectiveness','No automatic inspection or incident closure'],
        ['Effectiveness reviewer','Assigned action review in Incident','Effective / Ineffective decision','Inspection has no separate approval button'],
        ['Form designer','Draft Inspection forms and reusable questions','Administrator publishes in this example','No wider record editing implied'],
        ['Site reader','Read scoped records','None','Read scoped findings and reports'],
    ],'Priya can be an <strong>Inspection inspector at Dublin Maintenance</strong> and a <strong>Risk assessment owner in that same department</strong>. Sam can coordinate Cork inspections and investigate Cork incidents. Give each assignment an explicit scope; scanning a code should not extend it.')
    # Button choices avoid transient native select menus in the embedded browser.
    choices = '<div class="learning-choices" role="group" aria-label="Choose your learning role">'+''.join(f'<button class="button" type="button" data-learning-role="{k}" aria-pressed="{str(k=="admin").lower()}">{v["label"]}</button>' for k,v in profiles.items())+'</div>'
    team = re.sub(r'<label for="learning-role">.*?</select>', '<strong>What would you like to learn as?</strong>'+choices,team,flags=re.S)
    g = build.__globals__
    original = next(line for line in g['SCRIPT'].splitlines() if "document.getElementById('learning-role').addEventListener" in line)
    replacement = original.replace("document.getElementById('learning-role').addEventListener('change', e => { const profile = profiles[e.target.value];", "document.querySelectorAll('[data-learning-role]').forEach(button => button.addEventListener('click', () => { document.querySelectorAll('[data-learning-role]').forEach(item => item.setAttribute('aria-pressed', String(item === button))); const profile = profiles[button.dataset.learningRole];")
    g['SCRIPT'] = g['SCRIPT'].replace(original,replacement.rstrip()[:-3]+'}));')
    g['EXTRA_STYLE'] += '\n.learning-choices{display:flex;flex-wrap:wrap;gap:8px;margin:12px 0}.learning-choices .button{font-size:12px;text-align:left}.learning-choices [aria-pressed=true]{background:var(--ink);color:white;border-color:var(--ink)}.role-picker{display:block}.role-result{padding-top:8px}\n'
    chapters = [
        ('start','Start here','''<div class="grid two"><div class="card"><h3>Open the app beside this guide</h3><ol><li>Click <strong>Open prototype</strong> above.</li><li>Enter invitation code <code>482916</code>, then sign in with <code>admin@northstar.example</code> and <code>Demo123!</code>.</li><li>Expand <strong>Inspection</strong> and choose <strong>Overview</strong>.</li></ol><p>Already signed in? Start at step 3.</p></div><div class="card"><h3>Your first goal</h3><p>Check the sample ladder, record its condition, complete fieldwork and schedule the next check using the same QR label.</p><p><a href="#quick-demo">Try the 10-minute ladder exercise →</a></p><p><a href="#people">Meet the example team →</a></p></div></div><div class="note warm"><strong>Presentation edition.</strong> Use Alex’s login for every role. Changes remain in this app tab until reload/sign-out, then sample records return. Evidence retains filenames and reference links, not uploaded file contents. The bell previews live due reminders; no backend job or email delivery runs. Equipment questions are examples; follow your organisation’s procedures and manufacturer instructions.</div>'''),
        ('big-picture','The big picture','''<p>An <strong>inspection</strong> is a routine check of conditions at an area or item of equipment. A <strong>finding</strong> is a check marked Needs attention. A <strong>Risk assessment</strong> describes hazards, controls and scores. An <strong>audit</strong> checks a wider programme or process. Use the simple Inspection module for everyday checks.</p><div class="journey"><span>1. Schedule</span><b>→</b><span>2. Observe</span><b>→</b><span>3. Respond</span><b>→</b><span>4. Complete checks</span><b>→</b><span>5. Track follow-up</span></div><div class="grid two"><div class="card"><h3>Complete the fieldwork</h3><p>Every check has an answer/result and the inspection has a closing summary. Any issue has a recorded response.</p></div><div class="card"><h3>Resolve the problem</h3><p>A linked corrective action may still be open after fieldwork completes. Carry out its work and verify effectiveness in Incident.</p></div></div><p class="path">Business unit → Site → Location → Department</p><p>Selecting a department supplies its parent site. Example: <strong>Dublin Plant → Maintenance</strong>. Form visibility and related Risk assessment choices use that site.</p>'''),
        ('people','Who does what?',team),
        ('quick-demo','Your first ladder inspection',
            step(1,'Open the sample ladder','<p>Choose <strong>Inspection → Inspections</strong>, search for <code>INS-LAD001</code>, and open <strong>Ladder LAD-001 · condition check</strong>. It is assigned to Priya Shah, due today, using Ladder condition check v1.</p>','Checklist, Follow-up and History tabs; three unanswered checks.')+
            step(2,'Try the QR route','<p>Click <kbd>QR label</kbd>, inspect the equipment name and responsible person, then <kbd>Test QR link</kbd>. Alternatively, open the top-bar scan icon, type <code>INS-LAD001</code>, and choose <kbd>Open record</kbd>.</p>','The same ladder questionnaire opens. No paper printing or camera is required for this practice.')+
            step(3,'Record the observations','<p>Confirm Actual inspection date is today. In this fictional all-clear exercise, choose <strong>Yes</strong> for each of the three questions. In real work, record what you actually observe.</p>','Yes produces Pass; progress reaches 100%. The inspection is not complete yet.')+
            step(4,'Complete and plan the next check','<p>Enter a Closing summary, for example “Three checks recorded; no issues observed in this practice run.” Enter a future <strong>Next inspection date</strong> such as one month from today. Click <kbd>Complete inspection</kbd>.</p>','Completed status; the notice gives a new inspection reference and next date. The completed answers become read-only.')+
            step(5,'Reuse the original label','<p>Open <kbd>QR label → Test QR link</kbd> again, or type the original <code>INS-LAD001</code> in the scanner.</p>','A fresh unanswered questionnaire for the next date, with Priya and the same equipment. Its printed QR reference remains INS-LAD001.')+
            step(6,'Check reminders and history','<p>Open the bell, filter Responsible person to Priya, and check which upcoming/overdue items match the reminder rules. A next date outside seven days is not shown under the default upcoming rule. Read History on the completed record.</p>','The completed due-today ladder check is no longer a reminder. Its history and responses remain in the register.')+'<p class="small">To start again, reload the prototype. This resets all demo changes in that app tab.</p>'),
        ('screens','Find the right page',table(['Page','Use it for','First action'],[
            ['Overview','Work to complete, overdue inspections, open findings and completed fieldwork','Open a due inspection or finding'],
            ['Inspections','Search/filter the register; schedule and open checks','New inspection or open a row'],
            ['Findings','Track checks needing attention and their live linked status','Filter and open a finding'],
            ['Templates','Inspect published or draft Inspection forms','Open Form Builder to edit/publish'],
            ['Reports','Filtered inspection and finding registers','Export CSV or use browser Print / PDF'],
        ])+'<h3>Inside a record</h3><ul><li><strong>Checklist:</strong> answers, observations, responses, summary and evidence.</li><li><strong>Follow-up:</strong> issues and links to corrective work.</li><li><strong>History:</strong> schedule, progress, completion and routing entries.</li></ul><p>Use the Inspections register’s search, site, status and person filters to find older or archived checks. The Findings page tracks corrective work separately.</p>'),
        ('templates','Prepare the questionnaire','''<p>Sofia drafts forms; Alex publishes them in this suggested team arrangement.</p><ol><li>Open <strong>Configuration → Form Builder</strong>, or <kbd>Open Form Builder</kbd> from Inspection → Templates.</li><li>Use <strong>Create form</strong>, enter a name and select module <strong>Inspection</strong>.</li><li>Keep the supplied metadata fields. Add questions from Components or search for a previously created field and add it to the end. Reorder fields and enter their labels, options and guidance.</li><li>For Yes / No checks, use positive wording: “Are walkways clear?” Yes means Pass; No means Needs attention. Use other field types where appropriate and choose explicit results during inspection.</li><li>Configure required questions and site visibility, review the preview, then publish.</li><li>Return to Inspection and schedule with the published form.</li></ol><div class="note"><strong>Version snapshots.</strong> A scheduled inspection retains its captured questionnaire. Editing/publishing a form affects new inspections. Repeat or next-date scheduling uses the current available published version. A draft-only or site-unavailable form cannot schedule a check.</div><p>Starter forms: <strong>Workplace inspection</strong>, <strong>Equipment pre-use check</strong> and <strong>Ladder condition check</strong>. Their questions are demonstration content.</p>'''),
        ('schedule','Schedule or repeat an inspection','''<p>Sam coordinates the schedule; Priya or another named inspector carries out the check.</p><ol><li>Open <strong>Inspections → New inspection</strong>.</li><li>Enter an identifiable title, department, inspector, published template, scheduled date and area/equipment.</li><li>Add instructions describing what to check, then <kbd>Schedule inspection</kbd>.</li></ol><p>Use <kbd>Edit schedule</kbd> to change the title, inspector, date, area or instructions without discarding recorded work. The department and captured template remain fixed. Keep the equipment identifier consistent when a physical QR label is already attached.</p><div class="grid two"><div class="card"><h3>Same equipment, next check</h3><p>Enter Next inspection date when completing, or use <kbd>Repeat inspection</kbd>. A fresh record retains the original QR reference and clears old observations/evidence. Next-date completion requires a future date and no other outstanding check using that label.</p></div><div class="card"><h3>Different equipment</h3><p>Use <kbd>New inspection</kbd> and print its own label. Repeating the old ladder record would keep the old ladder’s QR identity.</p></div></div><p>There is no automatic inspection recurrence here. Next-date completion creates one scheduled check now; Repeat opens the scheduling form. If several checks share a label, scanning opens the earliest active outstanding check.</p>'''),
        ('conduct','Record checks and complete fieldwork','''<ol><li>Open the assigned record on <strong>Checklist</strong>. Set Actual inspection date to the day observed, today or earlier.</li><li>Answer each question and choose its result: Pass, Needs attention or N/A.</li><li>For N/A, explain why the check does not apply. For Needs attention, describe the issue and record a response.</li><li>Use <kbd>Save progress</kbd> if interrupted. Navigate within the same app session to return to saved work.</li><li>Add inspection evidence and a Closing summary. Optionally set Next inspection date.</li><li>Click <kbd>Complete inspection</kbd>.</li></ol><div class="note"><strong>100% means results are recorded.</strong> Completion also checks required answers, valid dates, N/A explanations, issue responses, critical immediate responses and the closing summary. Read the displayed error to find what is missing.</div><p>A No answer on a Yes / No question cannot be marked Pass. Other question types need an explicit appropriate result. Completed fieldwork is read-only. Archiving preserves the record and findings; restore an archived incomplete check before recording more work.</p>'''),
        ('responses','Respond when something needs attention',table(['Response','What to enter','Where work continues'],[
            ['Corrected on site','Describe the issue and the correction made immediately','Correction is retained in this check'],
            ['Corrective action','Issue, priority, owner and due date; click Create corrective action','Incident action workflow'],
            ['Incident','Issue, priority, owner and due date; click Create incident draft','Complete and submit the Incident report'],
        ])+'''<p><strong>Critical</strong> findings require an immediate response before routing or completion. Record what actually happened; a priority label alone is not a response.</p><h3>Try a second exercise: Cork loading bay</h3><ol><li>Open <code>INS-101</code> from the Inspections register.</li><li>Find the walkway question with worn pedestrian markings. Its observation, owner, priority and corrective response are already illustrated.</li><li>Click <kbd>Create corrective action</kbd> and open the resulting action.</li><li>Return to the source inspection and finish remaining required checks, then enter its closing summary and complete.</li><li>Open Findings: the corrective work stays open until its Incident effectiveness process resolves it.</li></ol><p>For a newly observed issue, you can also choose a same-site <strong>Related Risk assessment</strong> and click <kbd>Open risk</kbd>. This links the observation without changing the assessment’s score. Decide separately whether its controls or scores need revision.</p>'''),
        ('findings','Follow up across modules','''<p>The coordinator follows the issue; the action owner carries out work; the reviewer checks its effectiveness.</p><ol><li>Open <strong>Inspection → Findings</strong>. Filter by site, owner or status, and select a finding.</li><li>Use <kbd>Open action</kbd> or <kbd>Open incident</kbd> on the original check.</li><li>For an action, carry out its tasks/work, record completion evidence and request/record the effectiveness review in Incident. Effective work resolves the finding; ineffective work needs follow-up.</li><li>For an incident, finish required report questions, submit the draft, then complete its investigation/actions and closure requirements.</li><li>Use the source Inspection link in the Risk/Incident record to return to the exact inspection and highlighted check.</li></ol><div class="note"><strong>Completed inspection ≠ resolved finding.</strong> The inspection records what was observed. Its finding reads the live linked Incident status, owner and due date. Completing tasks alone does not prove effectiveness; creating an Incident draft alone does not submit or close it.</div><p>Once routed, the original observation is locked to preserve what was sent. Manage linked ownership, deadlines and progress in Incident. Finding evidence supports the observation; inspection-level evidence supports the overall visit. Evidence controls store filenames/descriptions/URLs only in this prototype.</p><p>If Incident creation is blocked, check that <strong>Incident → Settings</strong> has an active Inspection Finding type/subtype and a published report form selected. Required questions are completed in the generated draft, using Form Builder’s Incident template.</p><p><a href="incident-user-guide.html#actions">Incident actions guide →</a> · <a href="risk-user-guide.html#reviews">Risk review guide →</a></p>'''),
        ('qr','Print and scan equipment labels','''<div class="grid two"><div class="card"><h3>Prepare</h3><ol><li>Open an inspection and click <kbd>QR label</kbd>.</li><li>Check the equipment identifier, inspector and due date.</li><li>Set Label website address to your deployed HTTPS workspace for phone use.</li><li><kbd>Print</kbd> or <kbd>Download label</kbd>. Keep the clear white border around the code.</li><li>Attach it to the correct equipment and test it.</li></ol></div><div class="card"><h3>Use in the field</h3><ol><li>Open the app’s Workspace → Scan QR label or top-bar scan icon.</li><li>Tap Start camera, allow camera access and scan the label.</li><li>If needed, choose a QR image or enter its INS reference, then Open record.</li><li>Sign in if opening the QR link directly while signed out.</li><li>Complete the current questionnaire.</li></ol></div></div><p><strong>The label survives repeat checks.</strong> A repeat has its own inspection ID for history but keeps the original label reference. Scanning selects the earliest active unfinished check. With no unfinished check, it opens the most recent active completed record; use Repeat inspection to schedule the next one.</p><p>The ladder’s condition check <code>INS-LAD001</code> and its safe-use Risk assessment <code>RA-LAD001</code> have separate labels. Scanning the Risk code opens its approved periodic review, rather than this condition checklist.</p><div class="note warm"><strong>Access and demonstration limits.</strong> A QR identifies a record; it does not grant access or automatically complete it. Camera/image decoding runs on the device. Phones need the deployed HTTPS address; localhost is only for this computer. New demo records are not shared across devices and disappear on reload/sign-out. Use Test QR link or the seeded ladder references for this presentation.</div>'''),
        ('reminders','Understand due reminders','''<p>The bell displays a live preview of due work from enabled Scheduled jobs rules. Inspection reminders use the <strong>assigned inspector and scheduled date</strong>; Risk review reminders use the approved assessment’s <strong>owner and review date</strong>.</p><ol><li>Open <kbd>Due-date reminders</kbd> in the top bar.</li><li>Choose Responsible person to view Priya’s or Sam’s items.</li><li>Click a reminder to open the linked record.</li><li>Use <kbd>Manage reminder schedules</kbd> to open Configuration → Scheduled jobs.</li></ol><p>The default Daily equipment &amp; risk reminders rule covers the next seven days. Overdue jobs match late records. For the bell, a rule must be enabled and match the target, scope, lead/overdue threshold, owner recipients and in-app channel. An email-only rule is not displayed there.</p><p>Completing an inspection removes its old due item. A newly scheduled check appears when its date enters the matching window. Saving a Risk review updates its due date. Job test previews use these live records; other module samples remain illustrative.</p><div class="note"><strong>No messages are sent.</strong> This preview refreshes while the workspace is open. Running jobs in the background and sending automatic emails need production backend integration. Reminder rules do not create recurring inspections.</div>'''),
        ('reports','Read the overview and reports','''<p>Use the overview for a quick team conversation: which checks still need work, which are overdue, which findings remain open, and which fieldwork is completed? A completed fieldwork count does not mean all related corrective actions are closed.</p><ol><li>Open Reports to see the Inspection register and Finding register.</li><li>Apply search/site/status filters relevant to your meeting.</li><li>Use Export inspections or Export findings for a spreadsheet. Use your browser’s Print command to print the page or save it as PDF.</li><li>Open the original record for its answers, evidence references and history.</li></ol><p>Archived inspection findings remain traceable. Give readers a suitable site scope in the proposed role model. The current admin demo allows all records to be read.</p>'''),
        ('help','Questions and practice checklist','''<details><summary>Why is my form missing when scheduling?</summary><p>It must belong to Inspection, be Published, and have questions visible for the department’s site. Scheduled checks retain their snapshot; new publication affects new schedules.</p></details><details><summary>Why will Complete inspection not work?</summary><p>Read the displayed message. Check actual date, every result and required answer, N/A reasons, issue responses, critical immediate response and closing summary. Create a selected action/incident before completing.</p></details><details><summary>Why did my QR open an older check?</summary><p>It opens the earliest active unfinished check using that label. Complete or archive outstanding old checks as appropriate. If none remain, it opens the latest active completed record.</p></details><details><summary>Why can’t I set the next date?</summary><p>It must be a future valid date. A current published form must be available for the same site, and no other active unfinished check can already share the label.</p></details><details><summary>Why can’t my phone open the label or start the camera?</summary><p>Use the deployed HTTPS workspace address. A localhost label points to the device itself. Allow camera access when prompted; try a QR image or type the reference if camera access is unavailable.</p></details><details><summary>Why is a completed inspection’s finding still open?</summary><p>Its Incident corrective action needs effectiveness verification, or its Incident draft needs submission and closure. Inspection completion only finishes fieldwork.</p></details><details><summary>Can Priya or Sam sign in separately?</summary><p>Use admin@northstar.example for this presentation. Names explain proposed responsibilities; separate-user login and scoped permissions are not enforced.</p></details><details><summary>Why did changes disappear?</summary><p>App data is in memory. Reload or sign-out restores the seed data. This guide’s practice ticks use separate browser storage when available.</p></details>'''+checklist([
            'Find INS-LAD001 and identify its inspector and template.',
            'Use QR label → Test QR link or the scanner reference.',
            'Record three checks, a closing summary and a future next date.',
            'Complete and scan the original label to open a fresh questionnaire.',
            'Filter due reminders by Priya and understand the seven-day window.',
            'Create corrective follow-up from INS-101 and return to its source.',
            'Explain why completed fieldwork can have open findings.',
            'Find the Inspection form in Form Builder and its published version.',
        ])),
    ]
    build('inspection',chapters,profiles,'Routine checks,<br><em>clear follow-up.</em>','Learn how to schedule a check, scan equipment labels, record conditions and follow issues through to resolution. Start with one ladder, then explore at your own pace.','10-minute')

if __name__ == '__main__':
    update_risk()
    build_inspection()
