// Behaviour checks for audit routing, immutable snapshots and recurring calendars.
const fs = require("node:fs");
const path = require("node:path");
const assert = require("node:assert/strict");
const ts = require("typescript");
for (const ext of [".ts", ".tsx"]) require.extensions[ext] = (module, file) => module._compile(ts.transpileModule(fs.readFileSync(file, "utf8"), { compilerOptions: { module: ts.ModuleKind.CommonJS, jsx: ts.JsxEmit.ReactJSX, target: ts.ScriptTarget.ES2022 } }).outputText, file);
const m = require(path.resolve("app/audit-model.ts"));
const { initialForms } = require(path.resolve("app/form-builder.tsx"));
const i = require(path.resolve("app/incident-model.ts"));
const records = { users: [{ id:"user-1",name:"Alex Morgan" },{ id:"user-2",name:"Sam O'Brien" },{id:"user-3",name:"Priya Shah"}], businessUnits:[{id:"bu-1",name:"Operations"}],sites:[{id:"site-1",name:"Dublin",parentId:"bu-1"},{id:"site-2",name:"Cork",parentId:"bu-1"}],locations:[{id:"loc-1",name:"Production",parentId:"site-1"},{id:"loc-2",name:"Warehouse",parentId:"site-2"}],departments:[{id:"dep-1",name:"EHS",parentId:"loc-1"},{id:"dep-2",name:"Maintenance",parentId:"loc-1"},{id:"dep-3",name:"Logistics",parentId:"loc-2"}] };
let data=m.initialAuditData(initialForms),inc=i.initialIncidentData(initialForms);
let audit=data.audits.find(a=>a.id==="AUD-104");
assert.equal(m.progress(audit),0,"default findings must never count as answered");
const next={};
const classifications=["Major Non Conformance","Minor Non Conformance","Not Applicable","Opportunity for Improvement"];
m.questions(audit).forEach((q,n)=>next[q.id]={answer:n===2?"":"Yes",type:classifications[n],comment:"Verified evidence / corrective work described.",score:String([1,3,5,4][n]),recorded:true,closed:true});
let result=m.commitFindings(audit,next,inc,initialForms,records);
assert.equal(result.error,"");
assert.equal(result.incidents.incidents.length,inc.incidents.length+1);
assert.equal(result.incidents.actions.length,inc.actions.length+2);
assert.equal(result.incidents.incidents[0].assigned[0],"user-2");
assert.equal(result.incidents.incidents[0].draft,false);
assert.equal(result.incidents.incidents[0].type,"Audit Non Conformance");
assert.equal(result.incidents.actions[0].kind,"Preventive");
assert.equal(result.incidents.actions[1].kind,"Corrective");
assert.equal(m.progress(result.audit),100);
assert.equal(m.scoreSummary(result.audit).earned,8);
assert.equal(m.scoreSummary(result.audit).possible,15,"N/A excluded from possible points");
assert.equal(m.scoreSummary(result.audit).percentage,53);
const duplicate=m.commitFindings(result.audit,next,result.incidents,initialForms,records);
assert.equal(duplicate.incidents.incidents.length,result.incidents.incidents.length);
assert.equal(duplicate.incidents.actions.length,result.incidents.actions.length);
const changed=i.snapshot(next);changed["sc-clear"].type="Conforming";
assert.equal(m.commitFindings(result.audit,changed,result.incidents,initialForms,records).audit.findings["sc-clear"].type,"Major Non Conformance","confirmed finding is immutable");
assert.equal(m.commitFindings(audit,next,inc,initialForms.filter(f=>f.id!=="form-incident"),records).error.includes("Publish"),true,"major finding closure blocked without published report template");
const extraForms=i.snapshot(initialForms);extraForms.find(f=>f.id==="form-incident").fields.push({id:"custom-required",label:"Additional evidence",type:"Long text",required:true});
assert.equal(m.commitFindings(audit,next,inc,extraForms,records).incidents.incidents[0].draft,true,"unanswered custom incident requirements stay Draft");
const thirdParty={...audit,auditeeKind:"Third party",auditee:"TP-1"};
assert.equal(m.commitFindings(thirdParty,next,inc,initialForms,records).incidents.incidents[0].assigned[0],"user-1","external auditee falls back to lead");
const originalLabel=audit.template.fields.find(f=>f.id==="sc-clear").label;
const edited=i.snapshot(initialForms);edited.find(f=>f.id==="form-audit-score").fields.find(f=>f.id==="sc-clear").label="Changed question";
assert.equal(audit.template.fields.find(f=>f.id==="sc-clear").label,originalLabel,"source edits cannot mutate saved audit snapshot");
assert.equal(m.validScore({auditScore:{min:0,max:5,step:1}},"2.5"),false);
assert.equal(m.validScore({auditScore:{min:0,max:5,step:1}},""),false);
assert.equal(m.occurrence({start:"2027-01-31T09:00",frequency:"Monthly"},1),"2027-02-28T09:00");
assert.equal(m.occurrence({start:"2027-01-31T09:00",frequency:"Monthly"},2),"2027-03-31T09:00","month end must not drift");
assert.equal(m.occurrence({start:"2028-02-29T09:00",frequency:"Annually"},1),"2029-02-28T09:00");
const year=data.plans[0].end;
const rule={...data.rules[0],id:"RS-TEST",frequency:"Monthly",start:`${year}-12-31T10:30`,leadDays:7};
const generated=m.generateRule(rule,data,initialForms,records,3);
assert.equal(generated.error,"");assert.equal(generated.created,3);
assert.equal(generated.data.plans.length,data.plans.length+1);
assert.equal(generated.data.programmes.length,data.programmes.length+1);
assert.equal(generated.data.audits.at(-1).start,`${year+1}-02-28T10:30`);
assert.equal(generated.data.programmes.at(-1).managedBy,"Scheduler");
assert.equal(m.generateRule(rule,generated.data,initialForms,records,3).created,0,"generation is idempotent");
assert.equal(m.generateRule({...rule,active:false},data,initialForms,records).created,0);
assert.equal(m.rulePreview({...rule,until:`${year+1}-01-31`},data,6).length,2);
data.audits=data.audits.map(a=>a.id===result.audit.id?result.audit:a);
assert.ok(m.archiveBlock("audit",result.audit.id,data,result.incidents).includes("follow-up"));
assert.ok(m.archiveBlock("audit","AUD-101",data,inc).includes("Completed"));
assert.ok(m.archiveBlock("programme","PG-003",data,inc).includes("child audits"));
assert.equal(m.trails(data).filter(t=>!t.resolvedBy).length,1);
const trail=m.trails(data)[0];
data.audits.push({...i.snapshot(audit),id:"AUD-TRAIL",programme:trail.audit.programme,findings:{"sc-clear":{answer:"Evidence now verified",type:"Conforming",comment:"Certificate available",score:"5",recorded:true,closed:true,origin:{audit:trail.audit.id,field:trail.field.id}}}});
assert.equal(m.trails(data).find(t=>t.audit.id===trail.audit.id).resolvedBy,"AUD-TRAIL");
console.log("Audit behaviour checks passed: routing, locks, scoring, snapshots, draft safeguards, recurrence, rollover, deduplication, archives and audit trail.");
