// Behaviour checks for profile scoping, preserved evaluations, updates and integration.
const fs=require("node:fs"),path=require("node:path"),assert=require("node:assert/strict"),ts=require("typescript");
for(const ext of [".ts",".tsx"])require.extensions[ext]=(module,file)=>module._compile(ts.transpileModule(fs.readFileSync(file,"utf8"),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2022}}).outputText,file);
const m=require(path.resolve("app/law-model.ts")),i=require(path.resolve("app/incident-model.ts")),{initialForms}=require(path.resolve("app/form-builder.tsx"));
const records={businessUnits:[],users:[{id:"user-1",name:"Alex"},{id:"user-2",name:"Sam"}],sites:[{id:"site-1",name:"Dublin"},{id:"site-2",name:"Cork"}],locations:[{id:"loc-1",parentId:"site-1"},{id:"loc-2",parentId:"site-2"}],departments:[{id:"dep-1",parentId:"loc-1"},{id:"dep-2",parentId:"loc-1"},{id:"dep-3",parentId:"loc-2"}]};
let data=m.initialLawData(),profile=data.profiles[0];
assert.equal(m.profileChecklists(data,profile).length,5);
assert.equal(m.complianceSummary(data,data.profiles[1]).total,2,"excluded checklist removed from denominator");
assert.equal(m.complianceSummary(data,data.profiles[1]).score,45,"unassessed checklists excluded from rating average");
assert.equal(m.complianceSummary(data,{...profile,activities:[]}).score,null,"no scores must not imply full compliance");
let e=m.evaluationFor(data,profile.id,"CL-001");
assert.throws(()=>m.saveEvaluation(data,{...e,score:101},false),/0 to 100/);
assert.throws(()=>m.saveEvaluation(data,{...e,relevant:false,exclusionReason:""},false),/Explain/);
assert.throws(()=>m.saveEvaluation(data,{...e,reviewDate:"2026-02-31"},false),/valid/);
assert.throws(()=>m.saveEvaluation(data,{...e,departmentId:""},false),/department/);
const excluded=m.saveEvaluation(data,{...e,relevant:false,exclusionReason:"Covered elsewhere"},false);
assert.equal(m.evaluationFor(excluded,profile.id,"CL-001").evaluation,e.evaluation);
assert.equal(m.evaluationFor(excluded,profile.id,"CL-001").evidence.length,e.evidence.length);
const restored=m.saveEvaluation(excluded,{...m.evaluationFor(excluded,profile.id,"CL-001"),relevant:true},false);
assert.equal(m.evaluationFor(restored,profile.id,"CL-001").score,e.score);
const scopeRemoved={...profile,activities:profile.activities.filter(x=>x!=="Workplace transport")};
assert(!m.profileChecklists(data,scopeRemoved).some(c=>c.id==="CL-001"));
assert.equal(m.evaluationFor(data,profile.id,"CL-001").evaluation,e.evaluation,"activity changes must retain evidence");
const patch=m.sampleLawPackage(),next=m.validateContent(patch,data);
data={...data,versions:[...data.versions,next]};
assert.equal(m.profileContent(data,profile).version,"2026.Q3","import alone must not accept profile update");
assert(!m.profileChecklists(data,profile).some(c=>c.id==="CL-005"));
const accepted=m.acceptContent(data,profile.id);profile=accepted.profiles[0];
assert.equal(profile.version,"2026.Q4");
assert.equal(accepted.profiles[1].version,"2026.Q3","other profiles keep old snapshot");
assert(m.profileChecklists(accepted,profile).some(c=>c.id==="CL-005"),"matching new activity checklist appears");
assert.equal(m.evaluationFor(accepted,profile.id,"CL-001").needsReview,true);
assert.equal(m.evaluationFor(accepted,profile.id,"CL-002").needsReview,false,"unchanged items remain reviewed");
assert.equal(m.evaluationFor(accepted,profile.id,"CL-001").evaluation,e.evaluation);
assert.equal(accepted.tasks.length,data.tasks.length);assert.deepEqual(accepted.links,data.links);
assert.strictEqual(m.acceptContent(accepted,profile.id),accepted,"repeated acceptance is idempotent");
e=m.evaluationFor(accepted,profile.id,"CL-001");
assert.equal(m.evaluationFor(m.saveEvaluation(accepted,e,false),profile.id,"CL-001").needsReview,true);
assert.equal(m.evaluationFor(m.saveEvaluation(accepted,e,true),profile.id,"CL-001").needsReview,false);
const onlyLawChanged=m.validateContent({...patch,checklists:[]},m.initialLawData());
const lawChanged=m.acceptContent({...m.initialLawData(),versions:[m.initialLawData().versions[0],onlyLawChanged]},"LP-001");
assert.equal(m.evaluationFor(lawChanged,"LP-001","CL-001").needsReview,true,"associated legislation changes flag evaluation even if checklist text unchanged");
const bad=structuredClone(patch);bad.legislation[0].sourceUrl="javascript:alert(1)";assert.throws(()=>m.validateContent(bad,m.initialLawData()),/HTTP/);
const broken=structuredClone(patch);broken.checklists[0].legislationIds=["missing"];assert.throws(()=>m.validateContent(broken,m.initialLawData()),/references/);
assert.throws(()=>m.validateContent(patch,accepted),/newer/);
const dup=structuredClone(patch);dup.legislation.push(dup.legislation[0]);assert.throws(()=>m.validateContent(dup,m.initialLawData()),/Duplicate/);
const parent=structuredClone(patch);parent.legislation[0].parentId="LEG-003";assert.throws(()=>m.validateContent(parent,m.initialLawData()),/hierarchy/);
const source={profileId:"LP-002",checklistId:"CL-001",title:"Transport"};const incidents=i.initialIncidentData(initialForms);
const created=m.createLawIncident(source,"dep-3",initialForms,incidents);
assert.equal(created.type,"Non Compliance");assert.equal(created.draft,true);assert.deepEqual(created.lawSource,source);
assert.notStrictEqual(created.template,initialForms.find(f=>f.id===created.template.id),"incident form is a snapshot");
assert.throws(()=>m.createLawIncident(source,"dep-3",[],incidents),/published/);
const action=m.createLawAction(source,"dep-3","Verify segregation","user-2","2026-10-10");
assert.equal(action.kind,"Corrective");assert.deepEqual(action.lawSource,source);assert.equal(action.incidents.length,0);
const link={id:"LL-new",...source,kind:"action",recordId:action.id,context:"Gap"};const linked=m.linkLawRecord(data,link);assert.strictEqual(m.linkLawRecord(linked,{...link,id:"different"}),linked);
const task={...data.tasks[0],title:"Verify controls",departmentId:"dep-3",due:"2026-10-10"};m.validateTask(task,records,data.profiles[1]);
assert.throws(()=>m.validateTask({...task,departmentId:"dep-1"},records,data.profiles[1]),/profile site/);
assert.throws(()=>m.validateTask({...task,completed:true,completion:""},records,data.profiles[1]),/completion comment/);
console.log("Law behaviour checks passed: scope, metrics, exclusion/restore, preserved versions/evidence, acceptance, validation, source links and completion gates.");
